<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="/WEB-INF/tlds/cera_form.tld" %> 
<%@ taglib prefix="cera" uri="/WEB-INF/tlds/cera.tld" %> 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="robots" content="index,follow" />
		<meta name="author" content="${command.lastEditUserName}">
		<meta name="google-site-verification" content="JC96M8paj34ChCcPK0EAKWSzDJqocRo6rdSqnzPbIm4" />
		<meta name="description" content="${command.title}. ${command.markupBody}" />
		<meta name="keywords" content="Jhapak, Forum, Topics, community, ${command.taggedKeywords}" />
		<title>Jhapak - ${command.title}</title>
		<link rel="icon" type="image/png" href="img/link_Image.png"/>
		
		<link rel="publisher" href="https://plus.google.com/+Jhapak4u"/>
		<meta property="article:publisher" content="https://www.facebook.com/EraOfCommunities" />
		
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
  				"@context" : "http://schema.org",
  				"@type" : "Article",
  				"name" : "${command.title}",
  				"author" : {
    				"@type" : "Person",
    				"name" : "${command.lastEditUserName}"
  				},
  				"datePublished" : "${command.isoPostedOn}",
				"headline" : "${command.title}",
  				"image" : "${command.markupImage}",
  				"articleBody" : "${command.markupBody}",
  				"url" : "${communityEraContext.requestUrl}"
			}
		</script>
		
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="@EraCommunity">
		<meta name="twitter:title" content="${command.title}">
		<meta name="twitter:description" content="${command.markupBody}">
		<meta name="twitter:url" content="${communityEraContext.requestUrl}">
		<meta name="twitter:image:src" content="${command.markupImage}">
		
		<!-- Open Graph data -->
		<meta property="og:title" content="${command.title}" />
		<meta property="og:type" content="article" />
		<meta property="og:url" content="${communityEraContext.requestUrl}" />
		<meta property="og:image" content="${command.markupImage}" />
		<meta property="og:description" content="${command.markupBody}" />
		<meta property="og:site_name" content="Jhapak" />
		<meta property="article:published_time" content="${command.isoPostedOn}" />
		<meta property="article:modified_time" content="${command.isoPostedOn}" />

		<meta property="fb:admins" content="100001187666357" /> 
		
		<%@ include file="/WEB-INF/jspf/commHeader.jspf" %>
		<%@ include file="/WEB-INF/jspf/header2.jspf"%>
		<%@ include file="/WEB-INF/jspf/headerTag.jspf"%>
		
		<link rel="stylesheet" media="all" type="text/css" href="css/commBnnr.css" />
		<link rel="stylesheet" type="text/css" href="css/allMedia.css" />
		
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		
		<style type="">
			input.titleHeader {
			    background: #FFF none repeat scroll 0% 0%;
			    border: 1px solid #DADEE2;
			    font-size: 14px;
			    padding: 8px 6px;
			    color: #20394D;
			    width: 98%;
			    margin: 12px 0px;
			}
			
			#checkAvail p.availableFail {
				font-size: 12px;
				font-weight: bold;
				color: #AC0000;
				margin-bottom: 10px
			}
			
			.topHeader .heading {
				width: 600px; 
				color: #184A72; 
				margin-bottom: 2px;
				background: transparent none repeat scroll 0% 0%;
			}
			
			#container .left-panel .coverBody {
				color: #252525;
				direction: ltr;
				line-height: 1.6;
			}
			
			#container .left-panel .coverBody p {
			    line-height: inherit;
			    font-size: 14px;
			    margin: 0.5em 0px;
			}
			
			.extraWord {
				text-align: center;
				font-weight: normal;
				font-size: 13px;
			}
			
			.extraWord a {
				color: #66799f;
				font-weight: bold;
			}
			
			a.likunlik {
				font-size: 18px; 
				color: #2F3D4A;
			}
			
			a.likunlik:hover {
				color: #66799f;
			}
		</style>
		
		<script type="text/javascript">
			function editTitle(wikiEntryId, title){
				BootstrapDialog.show({
	                title: 'Edit title',
	                message: '<input id="edtTitle" name="title" class="titleHeader" type="text" value="'+title+'" style=""/><div id="checkAvail"></div>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                },{
	                	label: 'Go',
	                	cssClass: 'btn-primary',
	                    action: function(dialogRef){
	                	var newTitle = dialogRef.getModalBody().find('#edtTitle').val();
	                        $.ajax({url:"${communityEraContext.currentCommunityUrl}/wiki/updateWikiTitle.ajx?entryId="+wikiEntryId+"&title="+newTitle,success:function(result){
		                        if(result.iserror) {
		                        	dialogRef.getModalBody().find('#checkAvail').html(result.titleError);
		                        } else {
		                        	$("#topTitle").html(newTitle);
		                        	dialogRef.close();
		                        }
	            	    	  }});
	                    }
	                }]
	            });
			}
		
			function subscribeWikiEntry(wikiEntryId){
				var isAuthenticated = ${communityEraContext.userAuthenticated};
			    if (!isAuthenticated) {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Follow this Wiki page',
		                message: '<p class="addTagHeader">You are not logged-in.<br/> Please login first to follow this Wiki page. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	$.ajax({url:"${communityEraContext.currentCommunityUrl}/wiki/followWikiEntry.ajx?id="+wikiEntryId,success:function(result){
			    	    $("#subscribeWikiEntry").html(result);
			    	  }});
			    }
			}
		
			function deleteWikiEntry(entryId){
				var	msg = "Are you sure you want to remove latest version of this wiki page.<br />";
				msg += "To remove this wiki page completely (with all revisions) go to <a href='${communityEraContext.currentCommunityUrl}/wiki/wikiHistory.do?entryId="+entryId+"'>Revision history</a> and click &#39;Delete this Wiki page&#39;.";
				var href="${communityEraContext.currentCommunityUrl}/wiki/wikiDelete.do?id="+entryId;
				BootstrapDialog.show({
	                type: BootstrapDialog.TYPE_WARNING,
	                title: 'Remove latest version of this page',
	                message: '<p class="extraWord">'+msg+'</p>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                },{
	                	label: 'Go',
	                	cssClass: 'btn-warning',
	                    action: function(dialogRef){
	                        window.location.href=href;
	                    }
	                }]
	            });
			}

			function unSubscribeWikiEntry(wikiEntryId){
				BootstrapDialog.show({
	                type: BootstrapDialog.TYPE_WARNING,
	                title: 'Delete this Wiki Page',
	                message: '<p class="extraWord">You will no longer be able to receive email alerts for updates to this wiki page.</p>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                },{
	                	label: 'Go',
	                	cssClass: 'btn-warning',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                        $.ajax({url:"${communityEraContext.currentCommunityUrl}/wiki/stopFollowingWikiEntry.ajx?id="+wikiEntryId,success:function(result){
	            	    	    $("#subscribeWikiEntry").html(result);
	            	    	  }});
	                    }
	                }]
	            });
			}
		
			function likeEntry(itemId) 
			{ 
			    var isAuthenticated = $("#isAuthenticated").val();
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in.<br/> Please login first to like / unlike. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	$.ajax({url:"${communityEraContext.contextUrl}/wiki/likeWikiEntry.ajx?wikiEntryId="+itemId,success:function(result){
			    	    if (result.newLType == "Like") {
			    	    	$("#likeUnike-"+itemId).html("<i class='fa fa fa-thumbs-up'></i>");
						} else {
							$("#likeUnike-"+itemId).html("<i class='fa fa fa-thumbs-down'></i>");
						}
			    	    $("#likeSpan-"+itemId).html(result.count);
			    	  }});
			    }
			}
		</script>
	</head>
	
	<body id="communityEra">
		<%@ include file="/WEB-INF/jspf/topHeader.jspf" %>
		<div class="commBanr">
			<div class="bnrImg" style="background-image:url(${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&imgType=Banner&communityId=${communityEraContext.currentCommunity.id});" >
				<div class="innerPanl">
					<div class="carousel_caption">
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Private'}">
							<h4><i class="fa fa-lock" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Protected'}">
							<h4><i class="fa fa-shield" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Public'}">
							<h4><i class="fa fa-globe" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<p>${communityEraContext.currentCommunity.welcomeText}</p>							
					</div>
					
					<div class="menuContainer">
						<ul id="gn-menu" class="gn-menu-main">
							<li><a href="${communityEraContext.currentCommunityUrl}/wiki/showWikiEntries.do"><i class="fa fa-book" style="margin-right: 8px;"></i>Wikis</a></li>
							<li>
								<nav id="menu">
						    		<input type="checkbox" id="toggle-nav"/>
						    		<label id="toggle-nav-label" for="toggle-nav"><i class="fa fa-bars"></i></label>
						    		<div class="box">
							    		<ul>
							    			<li><a href="${communityEraContext.currentCommunityUrl}/home.do"><i class="fa fa-home" style="margin-right: 8px;"></i>Home</a></li>
							    			<c:forEach items="${communityEraContext.enabledFeatureNamesForCurrentCommunity}" var="feature">
												<c:if test="${feature == 'Assignments'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/assignment/showAssignments.do"><i class="fa fa-briefcase" style="margin-right: 8px;"></i>Assignments</a></li>
												</c:if>
												<c:if test="${feature == 'Blog'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/blog/viewBlog.do"><i class="fa fa-quote-left" style="margin-right: 8px;"></i>Blogs</a></li>
												</c:if>
												<c:if test="${feature == 'Forum'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/forum/showTopics.do"><i class="fa fa-comments-o" style="margin-right: 8px;"></i>Forums</a></li>
												</c:if>
												<c:if test="${feature == 'Members'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/connections/showConnections.do"><i class="fa fa-user-plus" style="margin-right: 8px;"></i>Members</a></li>
												</c:if>
												<c:if test="${feature == 'Library'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/library/showLibraryItems.do"><i class="fa fa-folder-open" style="margin-right: 8px;"></i>Library</a></li>
												</c:if>
												<c:if test="${feature == 'Events'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/event/showEvents.do"><i class="fa fa-calendar-check-o" style="margin-right: 8px;"></i>Events</a></li>
												</c:if>
											</c:forEach>
							    		</ul>
						    		</div>
						    	</nav>
					    	</li>
						</ul>
					</div><!-- /container -->
					
					<div class="groups">
						<div class="picture">
							<c:choose>
								<c:when test="${communityEraContext.currentCommunity.logoPresent}">		
									<img src="${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&communityId=${communityEraContext.currentCommunity.id}" width="290" height="290" /> 
								</c:when>
								<c:otherwise>
									<img src="img/community_Image.png" id="photoImg" width="290" height="290" />
								</c:otherwise>
							</c:choose>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="container">
			<div class="left-panel">
			<input type="hidden" id="isAuthenticated" name="isAuthenticated" value="${communityEraContext.userAuthenticated}" />
			<div class="commSection">
				<div class="paginatedList" style="margin: 0px 0px 10px auto; padding: 0px;">	
					<div class="topSection" style="padding: 0px;">
						<div class="menus" style="float: left; width: 100%; border-bottom: 1px solid #D8D8D8; padding: 0px 10px 10px;">
							<ul style="margin-top: 6px;">
								<li><a class="heaedrMenu selectMenu"href="${communityEraContext.currentCommunityUrl}/wiki/wikiDisplay.do?entryId=${command.entryId}" style="font-size: 14px; font-weight: bold;">Page</a></li>
								<li><a class="heaedrMenu" href="${communityEraContext.currentCommunityUrl}/wiki/wikiDiscussionDisplay.do?entryId=${command.entryId}" style="font-size: 14px; font-weight: bold;">Discussion</a></li>
								<li><a class="heaedrMenu" href="${communityEraContext.currentCommunityUrl}/wiki/wikiHistory.do?entryId=${command.entryId}" style="font-size: 14px; font-weight: bold;">History</a></li>
							</ul>
						</div>
						<div style="padding: 10px 10px 5px; display: inline-block;">
							<div class='leftImg'>
								<c:choose>
									<c:when test="${command.photoPresent}">	
										<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref">
										 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.posterId}"/></a>	
									</c:when>
									<c:otherwise>
										<img src="img/user_icon.png" />
									</c:otherwise>
								</c:choose>
							</div>
							<div class="topHeader" >
								<div class="heading">
									<span style="font-size: 20px; font-weight: bold;" id="topTitle">${command.title}</span>
								</div>
								<div class="subHeader" style="width: 666px;">
									<c:if test= "${command.versionCount <= 1}" >
										Created by <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" class='memberInfo'
										title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.posterId}" >${command.lastEditUserName}</a> on ${command.datePostOn}
									</c:if>
									<c:if test= "${command.versionCount > 1}" >
										<c:choose>
											<c:when test="${command.currentVersion}">
												Revision as of <fmt:formatDate pattern="kk:mm, dd MMM yyyy" value="${command.dateOnPost}" /> by <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" class='memberInfo'
												title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.posterId}" >${command.lastEditUserName}</a>
											</c:when>
											<c:otherwise>
												This is an old revision of this page, as edited by <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" class='memberInfo'
												title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.posterId}" >${command.lastEditUserName}</a> at <fmt:formatDate pattern="kk:mm, dd MMM yyyy" value="${command.dateOnPost}" />. The present address (URL) is a permanent link to this revision, which may differ significantly from the current revision.
											</c:otherwise>
										</c:choose>
									</c:if>
								</div>
								<c:if test="${not empty command.taggedKeywords}">
									<div class="subHeader">
										<i class='fa fa-tags' style='font-size: 14px; margin-right: 4px;'></i>${command.taggedKeywords}
									</div>
								</c:if>
							</div> 
							<div class="menus" style="width: 100%; margin-top: 8px;">
								<ul style="margin-top: 6px; float: right;">
									<c:if test="${command.currentVersion}">
										<c:if test="${command.member || communityEraContext.userSysAdmin}">
											<li><a href="${communityEraContext.currentCommunityUrl}/wiki/editWiki.do?entryId=${command.entryId}" title="Edit this Article">
											<i class='fa fa-pencil' style='margin: 0px 4px; font-size: 14px;'></i>Edit</a></li>
										</c:if>
										
										<c:if test="${communityEraContext.userCommunityAdmin || communityEraContext.userSysAdmin}">
											<li><a href="javascript:void(0);" onclick="editTitle(&#39;${command.entryId}&#39;, &#39;${command.title}&#39;);" title="Edit title">
											<i class='fa fa-pencil' style='margin: 0px 4px; font-size: 14px;'></i>Edit Title</a></li>
										</c:if>
								
										<c:if test="${communityEraContext.userCommunityAdmin || communityEraContext.userSysAdmin}">
											<li><a href="javascript:void(0);" onclick="deleteWikiEntry(&#39;${command.entryId}&#39;);">
											<i class='fa fa-remove' style='margin: 0px 4px; font-size: 14px;'></i>Delete current version</a></li>
										</c:if>
										
										<c:if test="${command.rollbackPossible && (command.member || communityEraContext.userSysAdmin)}">
											<li><a href="${communityEraContext.currentCommunityUrl}/wiki/wikiRestore.do?entryId=${command.entryId}">
												<i class='fa fa-undo' style='margin: 0px 4px; font-size: 14px;'></i>Restore previous version</a></li>
										</c:if>            
										<c:if test="${command.currentUserSubscribed}">
											<li id="subscribeWikiEntry"><a onclick="unSubscribeWikiEntry(${command.entryId});" href="javascript:void(0);"
													onmouseover="tip(this,'Unsubscribe from email alerts for updates to this wiki page')">Stop Following this Wiki page</a></li>
										</c:if>
										<c:if test="${not command.currentUserSubscribed}">
											<li id="subscribeWikiEntry"><a onclick="subscribeWikiEntry(${command.entryId});" href="javascript:void(0);"
											 		onmouseover="tip(this,'Get email alerts for updates to this wiki page')">Follow this Wiki page</a></li>
										</c:if>
									</c:if>
								</ul>
							</div>
						</div>
					</div>
					
					<div class="inboxAds">
						<c:if test="${communityEraContext.production}">
							<!-- CERA_RES -->
							<ins class="adsbygoogle"
							     style="display:block"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="3781277785"
							     data-ad-format="auto"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
					
					<div class="coverBody">
						${command.displayBody}
					</div>
					
					<div class="inboxAds">
						<c:if test="${communityEraContext.production}">
							<!-- CERA_RES -->
							<ins class="adsbygoogle"
							     style="display:block"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="3781277785"
							     data-ad-format="auto"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
					
					<c:forEach items="${command.wikiEntrySections}" var="row">
						<div class="sections" style="margin: 0px 10px;">
			      			<h2 class="secHeader"><span>${row.sectionTitle}</span></h2>
			      			<div class="coverBody">${row.sectionBody}</div>
				      	</div>
			      	</c:forEach>
			      	
			      	<div class="inboxAds">
			      		<c:if test="${communityEraContext.production}">
							<!-- CERA_RES -->
							<ins class="adsbygoogle"
							     style="display:block"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="3781277785"
							     data-ad-format="auto"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
					
					<div class="topSection" style="border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;">
						<div>
							<ul class="bottSecLst">
								<li>
									<c:choose>
										<c:when test="${command.creatorPhotoPresent}">						 
											 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.creatorId}" title="${command.creatorName}"/>
										</c:when>
										<c:otherwise>
											<img src="img/user_icon.png" title="${command.creatorName}"/>
										</c:otherwise>
									</c:choose>
									<span title="${command.createdOnHover}">${command.createdOn}</span>
									<h4 style="margin-left: 16px;">created</h4>
								</li>
								<c:if test="${command.versionCount > 0}">
									<li>
										<c:choose>
											<c:when test="${command.photoPresent}">						 
												 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.posterId}" title="${command.lastEditUserName}"/>
											</c:when>
											<c:otherwise>
												<img src="img/user_icon.png" title="${command.lastEditUserName}"/>
											</c:otherwise>
										</c:choose>
										<span title="${command.datePostOnHover}">${command.datePostOn}</span>
										<h4 style="margin-left: 16px;">current</h4>
									</li>
								</c:if>
								<li>
									<span title="${command.versionCount}">${command.versionCount}</span>
									<h4>revisions</h4>
								</li>
								<li>
									<span title="Last viewed at ${command.lastVisitTime}">${command.visitCount}</span>
									<h4>views</h4>
								</li>
								<li>
									<span id="likeSpan-${command.id}">
										${command.likeCount}
									</span>
									<h4>likes</h4>
								</li>
								<li style="float: right; margin: 6px 12px;">
									<span>
										<c:choose>
											<c:when test="${command.alreadyLike}">
												<a id="likeUnike-${command.id}" href="javascript:void(0);" onclick="likeEntry(${command.id});" class='likunlik' ><i class="fa fa fa-thumbs-down"></i></a>
											</c:when>
											<c:otherwise>
												<a id="likeUnike-${command.id}" href="javascript:void(0);" onclick="likeEntry(${command.id});" class='likunlik' ><i class="fa fa fa-thumbs-up"></i></a>
											</c:otherwise>
										</c:choose>
									</span>
								</li>
							</ul>
						</div>
						<div>
						</div>
					</div>
					
					<div class="topSection" style="border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;">
						<div>
							<ul class="bottSecLst">
								<li style="margin: 0px;">
									<c:if test="${command.visitCount > 1}">
										<h4 style="">Thanks to all contributors for creating a page that has been read ${command.visitCount} times.</h4>
									</c:if>
									<c:if test="${command.visitCount <= 1}">
										<h4 style="">Thanks to all contributors for creating this page.</h4>
									</c:if>
									
									<c:forEach items="${command.contributors}" var="row" varStatus="status">
										<div style="float: left; position: relative; margin: 3px 0px;">
											<span class="contbCount">${row.contributionCount}</span>
											<c:choose>
												<c:when test="${row.contributorPhotoPresent}">						 
													 <img class="contbImg" src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${row.contributorId}" title="${row.contributorName}"/>
												</c:when>
												<c:otherwise>
													<img class="contbImg" src="img/user_icon.png" title="${row.contributorName}"/>
												</c:otherwise>
											</c:choose>
										</div>
									</c:forEach>
									
								</li>
							</ul>
						</div>
					</div>
						
				</div><!-- /.paginatedList --> 
			</div> <!-- .commSection -->
		</div> <!-- .left-pannel -->
			
		<div class="right-panel">
			<div class="inboxAds" style="display: inline-block; width: 100%;">
				<c:if test="${communityEraContext.production}">
					<!-- CERA_RP_R -->
					<ins class="adsbygoogle"
					     style="display:inline-block;width:300px;height:250px"
					     data-ad-client="ca-pub-8702017865901113"
					     data-ad-slot="4553333789"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
				</c:if>
			</div>
			
			<div class="inbox">
				<div class="eyebrow">
					<span><i class="fa fa-tags" style="margin-right: 2px;"></i>Popular Tags</span>
				</div>
				<div id="cloud" class="communities"></div>
				<div id="waitCloudMessage" style="display: none;">
					<div class="cssload-square" style="width: 13px; height: 13px;">
						<div class="cssload-square-part cssload-square-green" style="width: 13px; height: 13px;"></div>
						<div class="cssload-square-part cssload-square-pink" style="width: 13px; height: 13px;"></div>
						<div class="cssload-square-blend" style="width: 13px; height: 13px;"></div>
					</div>
				</div>
				<div id="cloudList" style="display: none; " class="communities"></div>
				<ul id="cloudTabs">
					<c:choose>
						<c:when test="${command.toggleList == 'true'}">
							<h3 class="selectedCloudTab" id="hCloud" style="display: none; float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
							<a href="javascript: toggle()" style="float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
							<h3 class="selectedCloudTab" style="float:right;" id="hCloudList">List</h3>
							<a href="javascript: toggle()" id="aCloudList" style="display: none; float:right; color: #66799f;">List</a>
						</c:when>
						<c:otherwise>
							<h3 class="selectedCloudTab" id="hCloud" style="float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
							<a href="javascript: toggle()" style="display: none; float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
							<h3 class="selectedCloudTab" style="display: none; float:right;" id="hCloudList">List</h3>
							<a href="javascript: toggle()" id="aCloudList" style="float:right; color: #66799f;">List</a>
					  	</c:otherwise>
					</c:choose>
				</ul>
			</div>
			
			<div class="inboxAds" style="display: inline-block; width: 100%;">
				<c:if test="${communityEraContext.production}">
					<!-- CERA_RP_R -->
					<ins class="adsbygoogle"
					     style="display:inline-block;width:300px;height:250px"
					     data-ad-client="ca-pub-8702017865901113"
					     data-ad-slot="4553333789"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
				</c:if>
			</div>
			</div>
		</div>
		<%@ include file="/WEB-INF/jspf/footer.jspf" %>
		<%@ include file="/WEB-INF/jspf/extraFooter.jspf" %>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57b6850a24ae6e28"></script>
	</body>
</html>							