<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="/WEB-INF/tlds/cera_form.tld" %> 
<%@ taglib prefix="cera" uri="/WEB-INF/tlds/cera.tld" %> 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="robots" content="index, follow" />
		<meta name="author" content="${command.posterName}">
		<meta name="google-site-verification" content="JC96M8paj34ChCcPK0EAKWSzDJqocRo6rdSqnzPbIm4" />
		<meta name="description" content="Jhapak, ${command.name}. ${command.displayBody} ${command.address}" />
		<meta name="keywords" content="Jhapak, event, community, ${command.keywords}" />
		<title>${command.name} - Jhapak</title>
		
		<link rel="canonical" href="${communityEraContext.requestUrl}" />
		<link rel="publisher" href="https://plus.google.com/+Jhapak4u"/>
		<meta property="article:publisher" content="https://www.facebook.com/EraOfCommunities" />
		
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
  				"@context" : "http://schema.org",
  				"@type" : "Event",
  				"name" : "${command.name}",
				"location":{
					"address":{
						"addressCountry":"${command.country}",
						"addressLocality":"${command.city}",
						"addressRegion":"${command.cstate}",
						"streetAddress":"${command.venue}",
						"postalCode":"${command.postalCode}",
						"@type":"PostalAddress"
					},
					"@type":"Place",
					"name":"${command.location}"},
  				"organizer":{
					"url":"${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}",
					"@type":"Organization",
					"name":"${command.posterName}"
				},
				"startDate":"${command.isoStartDate}",
				"endDate":"${command.isoEndDate}",
  				"image" : "${command.markupImage}",
  				"description":"${command.displayBody}",
  				"url" : "${communityEraContext.requestUrl}"
			}
		</script>
		
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="@EraCommunity">
		<meta name="twitter:title" content="${command.name}">
		<meta name="twitter:description" content="${command.displayBody}">
		<meta name="twitter:url" content="${communityEraContext.requestUrl}">
		<meta name="twitter:image:src" content="${command.markupImage}">
		<meta name="twitter:label1" value="Where" />
		<meta name="twitter:data1" value="${command.address}" />
		<meta name="twitter:label2" value="When" />
		<meta name="twitter:data2" value="${command.isoStartDate}" />
		
		<!-- Open Graph data -->
		<meta property="og:title" content="${command.name}" />
		<meta property="og:type" content="events.event" />
		<meta property="og:url" content="${communityEraContext.requestUrl}" />
		<meta property="og:image" content="${command.markupImage}" />
		<meta property="og:description" content="${command.displayBody}" />
		<meta property="og:site_name" content="Jhapak" />

		<meta property="event:location:latitude" content="${command.latitude}">
		<meta property="event:location:longitude" content="${command.longitude}">
		<meta property="event:start_time" content="${command.isoStartDate}">
		<meta property="event:end_time" content="${command.isoEndDate}">

		<meta property="fb:admins" content="100001187666357" />
		
		<link rel="icon" type="image/png" href="img/link_Image.png"/>
		
		<%@ include file="/WEB-INF/jspf/commHeader.jspf" %>
		<%@ include file="/WEB-INF/jspf/header2.jspf"%>
		<%@ include file="/WEB-INF/jspf/headerTag.jspf"%>
		
		<link rel="stylesheet" type="text/css" href="css/events.css" />
		<script type="text/javascript" src="js/cropbox.js"></script>
		<link rel="stylesheet" media="all" type="text/css" href="css/cropImage.css" />
		<link rel="stylesheet" media="all" type="text/css" href="css/commBnnr.css" />
		<link rel="stylesheet" type="text/css" href="css/allMedia.css" />
		
		<link rel="stylesheet" type="text/css" href="css/style.css" />
		
		<style type="text/css">
			br {
				margin: 2em;
				display: block;
				font-size: 10%;
			}
			
			#container .left-panel .commSection .paginatedList .details {
				width: 100%;
			}
			
			div.richtext, .commDesc {
				padding: 20px 20px 10px 20px;
				margin: 20px;
			}
			
			#container .left-panel .commSection .paginatedList .details .heading {
				line-height: 28px;
				font-weight: bold;
			    font-size: 22px;
			    font-weight: bold;
			    width: 85%;
			}
			
			#container .left-panel .commSection .paginatedList .details .pBold
			, #container .left-panel .commSection .paginatedList .details a.pBold{
				font-size: 17px;
				text-align: left;
				line-height: 21px;
				font-weight: 300;
				padding: 0px;
			}
			
			#container .left-panel .commSection .paginatedList .details .entry {
				top: 230px;
			}
			
			form .tagOutLine {
			    border: 2px solid #D5D5D5;
			    padding: 10px;
			    margin-bottom: 10px;
			    width: 600px;
			    height: auto;
			}
			
			.imageBox {
					position: relative;
					height: 200px;
					border: 1px solid #aaa;
					overflow: hidden;
					background-repeat: no-repeat;
					cursor: move;
				}
			
			.imageBox .thumbBox {
				position: absolute;
				width: 100%;
				height: 100%;
				background: none repeat scroll 0% 0% transparent;
			}
			
			.container {
			    position: absolute;
				top: 0%;
				left: 0%;
				right: 0%;
				bottom: 0%;
				width: 720px;
				padding: 0px;
			}
			
			.instructionDrag {
			    display: block;
			    line-height: 26px;
			    position: absolute;
			    text-align: center;
			    top: 95px;
			    width: 100%;
			}
			
			.instructions {
			    background: no-repeat scroll 9px 8px rgba(84, 97, 133, 0.4);
			    border-radius: 2px;
			    box-shadow: 0px 1px 0px rgba(0, 0, 0, 0.12) inset;
			    color: #FFF;
			    display: inline;
			    font-size: 13px;
			    font-weight: bold;
			    padding: 4px 9px 6px 9px;
			}
			
			.title {
			    background: #F5F5F5 none repeat scroll 0% 0%;
			    border-bottom: 1px solid #D2D4D7;
			    font-size: 16px;
			    font-weight: 500;
			    line-height: 22px;
			    color: #184A72;
			    overflow: hidden;
			    padding: 6px 11px 7px 14px;
			    text-transform: capitalize;
			}
			
			#container .left-panel .commSection .userListAlt,
			#container .left-panel .commSection .userList {
				font-size: 16px;
				line-height: 22px;
				font-weight: 500;
				min-height: 500px;
			}
			
			#container .left-panel .commSection .communities {
				border-width: 0px;
				margin: 0px;
			}
			
			#map_canvas {
			    width: 352px;
			    height: 330px;
			}
			
			#container .left-panel .commSection .userListAlt p span.counter{
			    border: 1px solid #D5D5D5;
			    width: 12px;
			    height: 8px;
			    padding: 2px 7px;
			    margin: 10px;
			    font-weight: 700;
			    border-radius: 5px;
			}
			
			#container .left-panel .commSection .paginatedList .details .heading span.evntDraft {
            	background: #66799f none repeat scroll 0% 0%;
            	text-decoration: none;
				display: inline-block;
				color: #FFF;
				padding: 7px 10px 6px;
				vertical-align: text-bottom;
				line-height: 12px;
				font-size: 12px;
				font-weight: bold;
				text-transform: uppercase;
				text-align: center;
				border-radius: 22px;
            }
		</style>
		
		<script src="https://maps.googleapis.com/maps/api/js"></script>
		<script>
	      function initialize(lat, lng) {
	        var mapCanvas = document.getElementById('map_canvas');
	        var mapOptions = {
	          center: new google.maps.LatLng(lat, lng),
	          zoom: 8,
	          mapTypeId: google.maps.MapTypeId.ROADMAP
	        }
	        var map = new google.maps.Map(mapCanvas, mapOptions)
	      }
	      //google.maps.event.addDomListener(window, 'load', initialize);
	    </script>
		
		<script type="text/javascript">
			function subscribeEvent(eventId){
				$.ajax({url:"${communityEraContext.contextUrl}/event/followEvent.ajx?id="+eventId,success:function(result){
		    	    $("#subscribeEvent").html(result);
		    	  }});
			}
		
			function unSubscribeEvent(eventId){
				BootstrapDialog.show({
	                type: BootstrapDialog.TYPE_WARNING,
	                title: 'Stop Following this Event',
	                message: '<p class="extraWord">You will no longer be able to receive email alerts for this Event.</p>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Go',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                        $.ajax({url:"${communityEraContext.contextUrl}/event/stopFollowingEvent.ajx?id="+eventId,success:function(result){
	            	    	    $("#subscribeEvent").html(result);
	            	    	  }});
	                    }
	                }, {
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                }]
	            });
			}
		
		    function uploadImage(eventId) 
			{ 
		    	var cropper = "";
		    	var options = {thumbBox: '.thumbBox', spinner: '.spinner', imgSrc: '' };
		    	
       	 		$('#file').trigger('click');
       	 		cropper = $('.imageBox').cropbox(options);
       	 		
       	 		$('#file').on('change', function(){
       	 		$('.instructionDrag').css({'display': 'inline'});
       	 		$('.zoomOut').css({'display': 'inline'});
       	 		$('.zoomIn').css({'display': 'inline'});
       			$('.btnSave').css({'display': 'inline'});

       			$('.zoomOut').on('click', function(){
       				cropper.zoomOut();
       			});

       			$('.zoomIn').on('click', function(){
       				cropper.zoomIn();
       			});

       			$('.btnSave').on('click', function(){
           			
       				var img = cropper.getBlob();
					var data = new FormData(); 
					data.append("file", img);
					$.ajax({url:"${communityEraContext.contextUrl}/event/saveEventPoster.img?eventId="+eventId,
						data: data,
					    enctype: 'multipart/form-data',
					    processData: false,  // do not process the data as url encoded params
					    contentType: false,   // by default jQuery sets this to urlencoded string
					    type: 'POST',
					    dataType: "json",
						success:function(result){
						var rs = result.eventId;
						$('.instructionDrag').css({'display': 'none'});
		       	 		$('.zoomOut').css({'display': 'none'});
		       	 		$('.zoomIn').css({'display': 'none'});
		       			$('.btnSave').css({'display': 'none'});

		       			$("#waitMessage").hide();
				    },
				 	// What to do before starting
			         beforeSend: function () {
				    	$("#waitMessage").show();
			         } 
	
		    	  });
       			});
                
                var reader = new FileReader();
                reader.onload = function(e) {
                    options.imgSrc = e.target.result;
                    cropper = $('.imageBox').cropbox(options);
                }
                reader.readAsDataURL(this.files[0]);
                this.files = [];
            });
			}
		</script>
		
		<script type="text/javascript">
		// Initial call
		$(document).ready(function(){
			var lat = ${command.latitude};
        	var lng = ${command.longitude};
        	initialize(lat, lng);

			$.ajax({url:"${communityEraContext.currentCommunityUrl}/community/cloudCommunity.ajx",dataType: "json",success:function(result){
				var aName = "<ul>";
				var fTagList = $("#fTagList").val();
				 $.each(result.aData, function() {
					 aName += "<li>";
					 aName += "<a href='${communityEraContext.currentCommunityUrl}/search/searchByTagInCommunity.do?filterTag="+this['tagText']+"&fTagList="+fTagList+"' ";
					 aName += "title='View "+this['count']+" items tagged with &#39;"+this['tagText']+"&#39;' class='size-"+this['cloudSet']+"' >"+this['tagText']+"</a>";
					 aName += "</li>";
						});
				 $("#cloud").html(aName+"</ul>");
				 
				 var bName = "<table >";
				 $.each(result.bData, function() {
					 bName += "<tr><td>";
					 bName += "<span class='size-"+this['cloudSet']+"'  ><a href='${communityEraContext.currentCommunityUrl}/search/searchByTagInCommunity.do?filterTag="+this['tagText']+"&fTagList="+fTagList+"' ";
					 bName += "title='View "+this['count']+" items tagged with &#39;"+this['tagText']+"&#39;' class='size-"+this['cloudSet']+"' >"+this['tagText']+"</a></span>";
					 bName += "</td><td style='color: rgb(42, 58, 71); float: right;'>["+this['count']+"]</td>";
					 bName += "</tr>";
						});
				 $("#cloudList").html(bName+"</table>");

				// Hide message
		        $("#waitCloudMessage").hide();
			    },
			 	// What to do before starting
		         beforeSend: function () {
		             $("#waitCloudMessage").show();
		         } 
		    });
		});
	</script>

	</head>
	<body id="communityEra">
		<%@ include file="/WEB-INF/jspf/topHeader.jspf" %>
		<div class="commBanr">
			<div class="bnrImg" style="background-image:url(${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&imgType=Banner&communityId=${communityEraContext.currentCommunity.id});" >
				<div class="innerPanl">
					<div class="carousel_caption">
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Private'}">
							<h4><i class="fa fa-lock" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Protected'}">
							<h4><i class="fa fa-shield" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Public'}">
							<h4><i class="fa fa-globe" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<p>${communityEraContext.currentCommunity.welcomeText}</p>							
					</div>
					<div class="menuContainer">
						<ul id="gn-menu" class="gn-menu-main">
							<li><a href="${communityEraContext.currentCommunityUrl}/event/showEvents.do"><i class="fa fa-calendar-check-o" style="margin-right: 8px;"></i>Events</a></li>
							<li>
								<nav id="menu">
						    		<input type="checkbox" id="toggle-nav"/>
						    		<label id="toggle-nav-label" for="toggle-nav"><i class="fa fa-bars"></i></label>
						    		<div class="box">
							    		<ul>
							    			<li><a href="${communityEraContext.currentCommunityUrl}/home.do"><i class="fa fa-home" style="margin-right: 8px;"></i>Home</a></li>
							    			<c:forEach items="${communityEraContext.enabledFeatureNamesForCurrentCommunity}" var="feature">
												<c:if test="${feature == 'Assignments'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/assignment/showAssignments.do"><i class="fa fa-briefcase" style="margin-right: 8px;"></i>Assignments</a></li>
												</c:if>
												<c:if test="${feature == 'Blog'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/blog/viewBlog.do"><i class="fa fa-quote-left" style="margin-right: 8px;"></i>Blogs</a></li>
												</c:if>
												<c:if test="${feature == 'Forum'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/forum/showTopics.do"><i class="fa fa-comments-o" style="margin-right: 8px;"></i>Forums</a></li>
												</c:if>
												<c:if test="${feature == 'Wiki'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/wiki/showWikiEntries.do"><i class="fa fa-book" style="margin-right: 8px;"></i>Wikis</a></li>
												</c:if>
												<c:if test="${feature == 'Members'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/connections/showConnections.do"><i class="fa fa-user-plus" style="margin-right: 8px;"></i>Members</a></li>
												</c:if>
												<c:if test="${feature == 'Library'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/library/showLibraryItems.do"><i class="fa fa-folder-open" style="margin-right: 8px;"></i>Library</a></li>
												</c:if>
											</c:forEach>
							    		</ul>
						    		</div>
						    	</nav>
					    	</li>
						</ul>
						<div class='actions2' id='connectionInfo'>
							<div class='btngroup' >
								
							</div>
						</div>
					</div><!-- /container -->
					<div class="groups">
						<div class="picture">
							<c:choose>
								<c:when test="${communityEraContext.currentCommunity.logoPresent}">		
									<img src="${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&communityId=${communityEraContext.currentCommunity.id}" width="290" height="290" /> 
								</c:when>
								<c:otherwise>
									<img src="img/community_Image.png" id="photoImg" width="290" height="290" />
								</c:otherwise>
							</c:choose>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="container"> 
			<div class="left-panel">
				<div class="commSection">
					<div class="paginatedList" style="margin-bottom: 20px; padding: 0px; margin-top: 0px;">	
						<c:choose>
							<c:when test='${command.eventPosterPresent}'>	
								<div class="inputForm2">
									<div id="photocontainer" style="cursor: inherit;">
										<img src="${communityEraContext.contextUrl}/event/eventPoster.img?id=${command.id}" width="100%"/>
									</div>
								</div>	
								<div class="details topSection" style="border-width: 1px 0px 1px; border-radius: 0px;">			 
							</c:when>
							<c:otherwise>
								<div class="details topSection" style="border-width: 1px 0px 1px;">
							</c:otherwise>
						</c:choose>
							<div class="heading">
								<span>
									${command.name}
									<c:if test='${command.status == 0}'>
										<span class="evntDraft">Draft</span>
									</c:if>
								</span>
							</div>
							<div class="person">
								<a class="pBold" href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" 
									class="memberInfo" title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.posterId}">${command.contactName}</a>
							</div>
							<div class="person pBold">
								<c:choose>
									<c:when test='${command.dateStarted != ""}'>					 
										 ${command.dateStarted}
										<c:if test='${command.dateEnded != ""}'>
											&nbsp;to&nbsp; ${command.dateEnded}
										</c:if>
									</c:when>
									<c:otherwise>
										<c:if test='${command.dateEnded != ""}'>
											--&nbsp;${command.dateEnded}
										</c:if>
									</c:otherwise>
								</c:choose>
							</div>
							<div class="person pBold">
								${command.city}, ${command.country}
							</div>
							
							<c:if test='${command.taggedKeywords != ""}'>
								<div class="person">
									<i class='fa fa-tags' style='font-size: 14px; margin-right: 4px;'></i>${command.taggedKeywords}
								</div>
							</c:if>
							<c:choose>
								<c:when test="${command.eventPosterPresent}">
									<div class="entry" id="likeUnike" style="top: 274px;"></div>
								</c:when>
								<c:otherwise>
									<div class="entry" id="likeUnike" style="top: 16px;"></div>
								</c:otherwise>
							</c:choose>
							<c:choose>
								<c:when test="${command.likeCount > 1}">
									<span>${command.likeCount} likes</span>
								</c:when>
								<c:otherwise>
									<span>${command.likeCount} like</span>
								</c:otherwise>
							</c:choose>
							<c:if test="${command.likeAllowed}">
								<c:choose>
									<c:when test="${command.alreadyLike}">
										<i class='a-icon-text-separator'></i><a href="javascript: likeEntry(${command.id}, 0)" class="euInfoSelect" style="font-weight: bold;" >Unlike</a>
									</c:when>
									<c:otherwise>
										<i class='a-icon-text-separator'></i><a href="javascript: likeEntry(${command.id}, 0)" class="euInfoSelect" style="font-weight: bold;" >Like</a>
									</c:otherwise>
								</c:choose>
							</c:if>
						
							<c:choose>
								<c:when test="${command.eventPosterPresent}">
									<div class="entry" id="likeUnike" style="top: 400px; left: 0px"></div>
								</c:when>
								<c:otherwise>
									<div class="entry" id="likeUnike" style="top: 180px; left: 0px"></div>
								</c:otherwise>
							</c:choose>
							<c:if test="${command.invitee && !command.replied}">
								<a onclick="replyInvitation(&#39;${command.id}&#39; , &#39;1&#39;)" href="javascript:void(0);">Join</a>
						 		<i class="a-icon-text-separator"></i><a onclick="replyInvitation(&#39;${command.id}&#39; , &#39;2&#39;)" href="javascript:void(0);">Maybe</a>
						 		<i class="a-icon-text-separator"></i><a onclick="replyInvitation(&#39;${command.id}&#39; , &#39;3&#39;)" href="javascript:void(0);">Decline</a>
							</c:if>
						
							<div class="menus">
								<ul style="margin-top: 6px;">
									<c:if test="${command.writeAllowed}">
										<li><a href="${communityEraContext.currentCommunityUrl}/event/editEvent.do?id=${command.id}" >Edit Event</a></li>
										<li><a href="${communityEraContext.currentCommunityUrl}/event/deleteEvent.do?id=${command.id}" >Delete Event</a></li>
									</c:if>
									
									<c:if test="${command.currentUserSubscribed}">
										<li id="subscribeEvent"><a onclick="unSubscribeEvent(${command.id});" href="javascript:void(0);"
												title="Unsubcribe from email alerts for this event">Stop Following this Event</a></li>
									</c:if>
									<c:if test="${not command.currentUserSubscribed}">
										<li id="subscribeEvent"><a onclick="subscribeEvent(${command.id});" href="javascript:void(0);"
										 		title="Get email alerts for this event">Follow this Event</a></li>
									</c:if>
								</ul>
							</div>
						</div>
					
						<div class="richtext">${command.displayBody}</div>
						<div class="userList">
							<div class="title">When & Where</div>
							<div id="mapDis" class="mapArea">
								<div id="map_canvas"></div> 
							</div>
							<div style="font-size: 13px; padding : 10px;">
								<b>
									<c:choose>
										<c:when test='${command.venue != ""}'>
											${command.venue}
										</c:when>
										<c:otherwise>
											${command.location}
										</c:otherwise>
									</c:choose>
								</b> <br />
								${command.address}
								<br />
								<c:choose>
									<c:when test='${command.dateStarted != ""}'>					 
										 ${command.dateStarted}
										<c:if test='${command.dateEnded != ""}'>
											&nbsp;to&nbsp; ${command.dateEnded}
										</c:if>
									</c:when>
									<c:otherwise>
										<c:if test='${command.dateEnded != ""}'>
											--&nbsp;${command.dateEnded}
										</c:if>
									</c:otherwise>
								</c:choose>
							</div>
						</div>
						<div class="userListAlt">
							<div class="title">Host</div>
							<div class="tipGroup2" style="height: unset;">
								<div class="tipImg">
									<c:choose>
										<c:when test="${command.posterPhotoPresent}">
											<c:url value="${communityEraContext.contextUrl}/pers/userPhoto.img?showType=m" var="photoUrl">
												<c:param name="id" value="${command.posterId}" />
											</c:url>
											<img src="${photoUrl}"  width='120' height='120' style=""/> 
										</c:when>
										<c:otherwise>
											<img src='img/user_icon.png'  width='120' height='120'/>
										</c:otherwise>
									</c:choose>
								</div>
								<div class="tipInfo">
									<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}" >${command.posterName}</a>
									<c:if test="${not empty command.posterWeb}">
										<p style="font-size: 12px;">
											<strong>Website:</strong>&nbsp;${command.posterWeb}
										</p>
									</c:if>
									<c:if test="${not empty command.posterMobile}">
										<p style="font-size: 12px;">
											<strong>Mobile:</strong>&nbsp;${command.posterMobile}
										</p>
									</c:if>
									<c:if test="${not empty command.posterEmail}">
										<p style="font-size: 12px;">
											<strong>Mobile:</strong>&nbsp;${command.posterEmail}
										</p>
									</c:if>
								</div>
								<c:if test="${not empty command.posterAbout}">
									<br />
									<p style="width: 320px; display: inline-block; padding: 10px;">
										${command.posterAbout}
									</p>
								</c:if>
							</div>
							<p style="margin-top: 10px;">
								<span class="counter">${command.eventCountForHost}</span>Events from ${command.posterName}
							</p>
						</div>
					</div>
				</div>
			</div>
			<div class="right-panel">
				<div class="inbox">
					<div class="eyebrow">
						<span><i class="fa fa-tags" style="margin-right: 2px;"></i>Popular Tags</span>
					</div>
					<div id="cloud" class="communities"></div>
					<div id="waitCloudMessage" style="display: none;">
						<div class="cssload-square" style="width: 13px; height: 13px;">
							<div class="cssload-square-part cssload-square-green" style="width: 13px; height: 13px;"></div>
							<div class="cssload-square-part cssload-square-pink" style="width: 13px; height: 13px;"></div>
							<div class="cssload-square-blend" style="width: 13px; height: 13px;"></div>
						</div>
					</div>
					<div id="cloudList" style="display: none; " class="communities"></div>
					<ul id="cloudTabs">
						<c:choose>
							<c:when test="${command.toggleList == 'true'}">
								<h3 class="selectedCloudTab" id="hCloud" style="display: none; float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
								<a href="javascript: toggle()" style="float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
								<h3 class="selectedCloudTab" style="float:right;" id="hCloudList">List</h3>
								<a href="javascript: toggle()" id="aCloudList" style="display: none; float:right; color: #66799f;">List</a>
							</c:when>
							<c:otherwise>
								<h3 class="selectedCloudTab" id="hCloud" style="float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
								<a href="javascript: toggle()" style="display: none; float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
								<h3 class="selectedCloudTab" style="display: none; float:right;" id="hCloudList">List</h3>
								<a href="javascript: toggle()" id="aCloudList" style="float:right; color: #66799f;">List</a>
						  	</c:otherwise>
						</c:choose>
					</ul>
				</div>
			</div>
		</div>
		<%@ include file="/WEB-INF/jspf/footer.jspf" %>
		<%@ include file="/WEB-INF/jspf/extraFooter.jspf" %>
	</body>
</html>