<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="/WEB-INF/tlds/cera_form.tld" %> 
<%@ taglib prefix="cera" uri="/WEB-INF/tlds/cera.tld" %> 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="google-site-verification" content="JC96M8paj34ChCcPK0EAKWSzDJqocRo6rdSqnzPbIm4" />
		<meta name="description" content="${command.displayDescription}" />
		<meta name="keywords" content="Jhapak, blog, free blog, personal blog, weblog, create blog, new blog, blog, personal, ${command.keywords}" />
		<title>${command.title} - Jhapak</title>
		<link rel="icon" type="image/png" href="img/link_Image.png"/>
		<link rel="canonical" href="${communityEraContext.requestUrl}" />
		<link rel="publisher" href="https://plus.google.com/+Jhapak4u"/>
		<meta property="article:publisher" content="https://www.facebook.com/EraOfCommunities" />
		<meta name="author" content="Jhapak">
		<meta name="robots" content="index, follow">
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
  				"@context" : "http://schema.org",
  				"@type" : "Article",
  				"name" : "${command.title}",
  				"author" : {
    				"@type" : "Person",
    				"name" : "${command.displayName}"
  				},
  				"datePublished" : "${command.isoPostedOn}",
				"headline" : "${command.title}",
  				"image" : "${command.markupImage}",
  				"articleBody" : "${command.markupBody}",
  				"url" : "${communityEraContext.requestUrl}"
			}
		</script>
		
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="@EraCommunity">
		<meta name="twitter:title" content="${command.title}">
		<meta name="twitter:description" content="${command.displayDescription}">
		<meta name="twitter:url" content="${communityEraContext.requestUrl}">
		<meta name="twitter:image:src" content="${command.markupImage}">
		
		<!-- Open Graph data -->
		<meta property="og:title" content="${command.title}" />
		<meta property="og:type" content="article" />
		<meta property="og:url" content="${communityEraContext.requestUrl}" />
		<meta property="og:image" content="${command.markupImage}" />
		<meta property="og:description" content="${command.displayDescription}" />
		<meta property="og:site_name" content="Jhapak" />
		<meta property="article:published_time" content="${command.isoPostedOn}" />
		<meta property="article:modified_time" content="${command.isoPostedOn}" />

		<meta property="fb:admins" content="100001187666357" /> 
		
		<%@ include file="/WEB-INF/jspf/commHeader.jspf" %>
		<%@ include file="/WEB-INF/jspf/header2.jspf"%>
		<%@ include file="/WEB-INF/jspf/headerTag.jspf"%>
		<link rel="stylesheet" media="all" type="text/css" href="css/profile.css" />
		<%@ include file="/WEB-INF/jspf/extraJs.jspf" %>
		<script type="text/javascript" src="js/qtip/memberInfoTip.js"></script>
		<link rel="stylesheet" type="text/css" href="css/allMedia.css" />
		
		<!--  Redefine this style to change file icon image -->
		<style type="text/css">
			#container .left-panel .nav-list ul li.selected {
			    width: 180px;
			}
			
			div.tag-set {
				margin-top: 10px;
			}
			
			.tag-dialog .modal-dialog .modal-body {
                height: 50px;
                padding : 20px;
            }
            
            form .tagOutLine {
            	width: 670px;
            }
            
            #container .left-panel .commSection .communities h2 {
			    padding: 0px;
			    margin: 10px 0px;
			}
			
			#container .left-panel h2 {
			    font-style: normal;
			    padding: 0px;
			    font-size: 14px;
			}
			
			.addTag-dialog .modal-dialog {
                width: 720px;
				margin: 30px auto;
                padding : 20px;
            }
		</style>
		
		<script type="text/javascript">
			var editor_0;
			function likeEntry(entryId, commentId) 
			{ 
			    var isAuthenticated = $("#isAuthenticated").val();
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="addTagHeader">You are not logged-in.<br/> Please login first to like / unlike. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else if (commentId > 0) {
			    	$.ajax({url:"${communityEraContext.contextUrl}/blog/likeBlogEntryComment.ajx?entryId="+entryId+"&commentId="+commentId,success:function(result){
			    	    $("#div-"+commentId).html(result);
			    	  }});
			    } else {
			    	$.ajax({url:"${communityEraContext.contextUrl}/blog/likeBlogEntry.ajx?blogEntryId="+entryId,success:function(result){
			    	    $("#likeUnike").html(result);
			    	  }});
			    }
			}

			function submitComment(){
			    var isAuthenticated = $("#isAuthenticated").val();
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="addTagHeader">You are not logged-in.<br/> Please login first to post a comment. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	document.getElementById('comment').value = editor_0.getData();
					document.submitCommentForm.action = "${communityEraContext.requestUrl}";
					document.submitCommentForm.submit();
			    }
			}

			function subscribeBlogEntry(blogEntryId){
				var isAuthenticated = ${communityEraContext.userAuthenticated};
			    if (!isAuthenticated) {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Following this Blog',
		                message: '<p class="addTagHeader">You are not logged-in.<br/> Please login first to start following this blog entry. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	$.ajax({url:"${communityEraContext.contextUrl}/blog/followBlogEntry.ajx?id="+blogEntryId,success:function(result){
			    		$("#subscribeBlogEntry").html(result);
			    	    $('.normalTip').qtip({ 
						    content: {
						        attr: 'title'
						    },
							style: {
						        classes: 'qtip-tipsy'
						    }
						});
			    	  }
			    	 });
			    }
			}
		
			function unSubscribeBlogEntry(blogEntryId){
				var isAuthenticated = ${communityEraContext.userAuthenticated};
			    if (!isAuthenticated) {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Stop following this Blog',
		                message: '<p class="addTagHeader">You are not logged-in.<br/> Please login first to stop following this blog entry. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_WARNING,
		                title: 'Stop Following this Blog Entry',
		                message: '<p class="addTagHeader">You will no longer be able to receive email alerts for this Blog Entry.</p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                },{
		                	label: 'Go',
		                	cssClass: 'btn-warning',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                        $.ajax({url:"${communityEraContext.contextUrl}/blog/stopFollowingBlogEntry.ajx?id="+blogEntryId,success:function(result){
		            	    	    $("#subscribeBlogEntry").html(result);
		            	    	  }});
		                    }
		                }]
		            });
			    }
			}

			function deleteBlogEntry(blogEntryId){
				var blogId = document.getElementById('blogId').value;
		    	BootstrapDialog.show({
	                type: BootstrapDialog.TYPE_WARNING,
	                title: 'Delete Blog Entry',
	                message: '<p class="addTagHeader">Are you sure you want to delete this Blog Entry?</p>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                },{
	                	label: 'Go',
	                	cssClass: 'btn-warning',
	                    action: function(dialogRef){
	                		window.location.href = "${communityEraContext.contextUrl}/blog/deleteBlogEntry.do?id="+blogEntryId+"&pbId="+blogId;
	                        dialogRef.close();
	                    }
	                }]
	            });
			}

			function submitTagAction(){
				var toElm = document.getElementById('addedTags');
				var toArray = toElm.value.split(' ');
				var isSpecialCharPresent = false;
				for (i=0; i<toArray.length; i++) { 				
					var str = toArray[i].toLowerCase();		
					if (str.match("[$&+,:;=?@#|'<>.-^*()%!]")) {
						isSpecialCharPresent = true;
						break;
					}
				}
				if (isSpecialCharPresent) {
					var type = BootstrapDialog.TYPE_DANGER;
			    	BootstrapDialog.show({
		                type: type,
		                title: 'Error',
		                message: 'Special characters like &, #, @, etc are not allowed in tags',
		                cssClass: 'tag-dialog',
		                closable: true,
		                closeByBackdrop: true,
		                closeByKeyboard: true,
		                draggable: true,
		                buttons: [{
		                	label: 'Close',
		                	cssClass: 'btn-danger',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
				} 
			}
			
			function addEditTag(tagName)
			{
				var toElm = document.getElementById('addedTags');
				var toArray = toElm.value.split(' ');
				var isAlreadyPresent = false;
				for (i=0; i<toArray.length; i++) { 
					if (toArray[i].replace( /^\s+/g, "" ) == tagName) {
						isAlreadyPresent = true;
					}
				}
				if (!isAlreadyPresent) {
					var sep = '';
					if (toElm.value != '') sep = ' ';
					toElm.value = toElm.value + sep + tagName;
				}
			}

			function addEditTags(parentType, blogEntryId) {
				$(".qtip").hide();
				BootstrapDialog.show({
	                title: 'Add/Edit tags for this Blog Entry',
	                message: function(dialog) {
						var $message = $('<div id="main" style="display: inline-block;width: 700px;"></div>');
			            return $message;
			        },
	                closable: true,
	                cssClass: 'addTag-dialog',
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                onshow: function(dialog) {
		                var addedtags = "";
			        	var form = "<div style='display:inline-block;'>";
			        		form += "<p class='addTagHeader'>A tag is a keyword / one word label which members can assign to any items in the community to categorize it. A tag make it easier to find related items. Popular tags appear in larger text in the tag cloud.<br /><br />";
			        		form += "<strong>Use space to separate tags. Special characters like &, #, @, etc are not allowed.</strong></p><br />";
			        		form += "<label for='txtKeywords' class='tagFieldLab'>Add Tags:</label>";
			        		form += "<input id='addedTags' name='tags' type='text' class='tagFieldInput' autocomplete='off'></input>";
			        		$.ajax({url:"${communityEraContext.contextUrl}/tag/mostPopularTags.ajx?parentType="+parentType+"&parentId="+blogEntryId,success:function(result){
			        			if (result.aData.length > 0) {
			        				form += "<p class='addTagHeader2' >Popular tags can also be reused. Just click to add to the tag list</p><p class='addTagHeader3'>";
			        				$.each(result.aData, function() {
			        					form += "<a href='javascript:void(0);' onclick='addEditTag(&#39;"+this['tagText']+"&#39;)' title='Click to add tag &#39;"+this['tagText']+"&#39; to the tag list'>"+this['tagText']+"</a>";
			        				});
			        				form += "</p>";
				        		}
			        			addedtags = result.tags;
			        			form += "</div>";
					            dialog.getModalBody().find('#main').html(form);
					            dialog.getModalBody().find('#addedTags').val(addedtags);
	            	    	  }});
			        },
	                buttons: [{
	                	label: 'Cancel',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                },
	                {
	                	label: 'Submit tags',
	                	cssClass: 'btn-primary',
	                    action: function(dialogRef){
	                		submitTagAction();
	                		var addedtags = document.getElementById('addedTags').value;
	                        $.ajax({url:"${communityEraContext.contextUrl}/tag/addTag.ajx?parentType="+parentType+"&parentId="+blogEntryId+"&tags="+addedtags,success:function(result){
	                        	if(result.tagCount > 0){
									$('#taggedKeywords').html(result.taggedKeyWords);
								}else{
									$('#taggedKeywords').html("");
								}
	                        	dialogRef.close();
	            	    	  }});
	                    }
	                }]
	            });
			}
		</script>
		
		<script type="text/javascript">
		// Initial call
		$(document).ready(function(){
			var config = {};
        	config.toolbarGroups = [
									{ name: 'colors', groups: [ 'colors' ] },
									{ name: 'insert', groups: [ 'insert' ] },
									{ name: 'basicstyles', groups: [ 'bold'] },
									{ name: 'styles', groups: [ 'size' ] },
                            	];
        	config.toolbarLocation = 'top';
        	config.removeButtons = 'Subscript,Superscript,Image,Flash,Table,Iframe,SpecialChar,HorizontalRule,PageBreak';
        	editor_0 = CKEDITOR.appendTo( 'editor', config, '' );
			normalQtip();
			memberInfoQtip();

			if(${command.pageCount} > 0){
				$("#pagination").jPaginator({ 
					nbPages:${command.pageCount},
					marginPx:5,
					length:6, 
					overBtnLeft:'#over_backward', 
					overBtnRight:'#over_forward', 
					maxBtnLeft:'#max_backward', 
					maxBtnRight:'#max_forward', 
					onPageClicked: function(a,num) { 
					$.ajax({url:"${communityEraContext.contextUrl}/blog/blogEntry.do?jPage="+num+"&beID="+$("#beID").val()+"&sortByOption="+$("#sortByOption").val(),dataType: "json",success:function(result){
						var sName = "";
						$.each(result.aData, function() {
							 var rowId = this['id'];
							 var blogEntryId = this['blogEntryId'];
							 sName += "<div class='internalPagination'><div class='leftImg'>";
							 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+this['posterId']+"&backlink=ref' class='memberInfo' ";
							 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+this['posterId']+"'>";
							 if(this['photoPresent']){
								 sName += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+this['posterId']+"' /></a>"; }
							 else {
								 sName += "<img src='img/user_icon.png'  /></a>";
							 }
	
							 sName += "</div><div class='details'><div class='person'><a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+this['posterId']+"&backlink=ref' ";
							 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+this['posterId']+"' class='memberInfo' style='padding:0px;'>"+this['displayName']+"</a><br /> commented on "+this['postedOn']+"</div>";
	
							 sName += "<div class='entry' id='div-"+rowId+"' >";
							 if(this['likeCommentCount'] > 1){
								 sName += "<span>"+this['likeCommentCount'] + " likes</span>";
							 } else {
								 sName += "<span>"+this['likeCommentCount'] + " like</span>";
							 }
							 
							 if (this['commentLikeAllowed']) {
								if (this['alreadyCommentLike']) {
									 sName += "<i class='a-icon-text-separator'></i><a href='javascript: likeEntry("+blogEntryId+", "+rowId+")' >Unlike</a>";
								} else {
									sName += "<i class='a-icon-text-separator'></i><a href='javascript: likeEntry("+blogEntryId+", "+rowId+")' >Like</a>";
								}
							 }
							sName += "</div>";
							sName += "<p>"+this['comment']+"</p></div></div><li class='lineseparater'></li>";
							
								});
						 $("#page").html(sName);
					    }});
					} 
				});
			}

			$.ajax({url:"${communityEraContext.contextUrl}/common/allEntryCloud.ajx?toolType=CommunityBlog&toolId=${command.blogId}",dataType: "json",success:function(result){
				var aName = "<ul>";
				var fTagList = $("#fTagList").val();
				 $.each(result.aData, function() {
					 aName += "<li>";
					 aName += "<a href='${communityEraContext.contextUrl}/search/searchByTagInCommunity.do?filterTag="+this['tagText']+"&fTagList="+fTagList+"' ";
					 aName += "title='View "+this['count']+" items tagged with &#39;"+this['tagText']+"&#39;' class='normalTip size-"+this['cloudSet']+"' >"+this['tagText']+"</a>";
					 aName += "</li>";
						});
					if(aName == "<ul>"){
						$("#cloud").html("<span style ='font-size: 12px; padding-left: 80px;'>No tags yet</span>");
					}else{
						$("#cloud").html(aName+"</ul>");
					}
				 
				 var bName = "<table >";
				 $.each(result.bData, function() {
					 bName += "<tr><td>";
					 bName += "<span><a href='${communityEraContext.contextUrl}/search/searchByTagInCommunity.do?filterTag="+this['tagText']+"&fTagList="+fTagList+"' ";
					 bName += "title='View "+this['count']+" items tagged with &#39;"+this['tagText']+"&#39;' class='normalTip size-1' >"+this['tagText']+"</a></span>";
					 bName += "</td><td style='color: rgb(42, 58, 71); float: right;'>["+this['count']+"]</td>";
					 bName += "</tr>";
						});
				 if(bName == "<table >"){
					$("#cloudList").html("<span style ='font-size: 12px; padding-left: 80px;'>No tags yet</span>");
				}else{
					$("#cloudList").html(bName+"</table>");
				}
				// Hide message
		        $("#waitCloudMessage").hide();
			    },
			 	// What to do before starting
		         beforeSend: function () {
		             $("#waitCloudMessage").show();
		         } 
		    });

		});
		</script>
	</head>

	<body id="communityEra">
		<%@ include file="/WEB-INF/jspf/topHeader.jspf" %>
		<div id="container" >
			<div class="left-panel" style="margin-top: -11px;">
				<input type="hidden" id="isAuthenticated" name="isAuthenticated" value="${communityEraContext.userAuthenticated}" />
				<input type="hidden" id="beID" name="beID" value="${command.id}" />
				<input type="hidden" id="blogId" name="blogId" value="${command.blogId}" />
				<div class="commSection">
					<div class="abtMe">
						<div class="cvrImg">
							<c:if test="${command.coverPresent}">
								<img src="${communityEraContext.contextUrl}/pers/userPhoto.img?imgType=Cover&showType=m&id=${command.posterId}" 
						 			width="750px" height="270px" />
						 	</c:if>
						</div>
						<div class='detailsConnection'>
							<h2 >
								<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" >${command.displayName}</a>
							</h2>
						</div>
						<div class="groups">
							<div class="picture">
								<c:choose>
									<c:when test="${command.photoPresent}">
										<c:url value="${communityEraContext.contextUrl}/pers/userPhoto.img?showType=m" var="photoUrl">
											<c:param name="id" value="${command.posterId}" />
										</c:url>
										<img src="${photoUrl}"  width='160' height='160' style=""/> 
									</c:when>
									<c:otherwise>
										<img src='img/user_icon.png'  width='160' height='160'/>
									</c:otherwise>
								</c:choose>
							</div>
						</div>
						<c:if test="${communityEraContext.currentUser.id != command.posterId}">
							<c:if test="${command.contactionAllowed}">				
								<div class='actions3' id='connectionInfo'>${command.returnString}</div>
							</c:if>
                       	</c:if>
					</div>
					<div class="nav-list">
						<ul>
							<li><a href="${communityEraContext.contextUrl}/pers/connectionCommunities.do?id=${command.posterId}">Communities</a></li>
							<li class="selected"><a href="${communityEraContext.contextUrl}/blog/personalBlog.do?id=${command.posterId}">Blogs</a></li>
							<li><a href="${communityEraContext.contextUrl}/pers/connectionList.do?id=${command.posterId}">Connections</a></li>
							<li><a href="${communityEraContext.contextUrl}/pers/mediaGallery.do?id=${command.posterId}">Gallery</a></li>
						</ul>
					</div>
						
					<div class="paginatedList" style="padding: 0px; margin: 0px 0PX 10px auto;">
						<div class="topSection" >
							<div class="leftImg">							
								<c:choose>
									<c:when test="${command.photoPresent}">						 
										 <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref">
										 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.posterId}"/></a>
									</c:when>
									<c:otherwise>
										<img src="img/user_icon.png" />
									</c:otherwise>
								</c:choose>
							</div>
							<div class="topHeader" >
								<div class="heading" style="width: 600px; color: #184A72; margin-bottom: 2px;">
									<span style="font-size: 20px; font-weight: bold;">${command.title}</span>
								</div>
								<div class="subHeader">
									Published by 
									<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.posterId}&backlink=ref" class='memberInfo'
									title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.posterId}" >${command.displayName}</a> on ${command.postedOn}
								</div>
								<div class="subHeader">
									<c:choose>
										<c:when test="${command.commentCount > 1}">
											${command.commentCount} comments<i class='a-icon-text-separator'></i>
										</c:when>
										<c:otherwise>
											${command.commentCount} comment<i class='a-icon-text-separator'></i>
										</c:otherwise>
									</c:choose>
									${command.visitCount} view<c:if test="${command.visitCount > 1}">s</c:if>
									<c:if test="${command.visitCount > 0}">
										 <i class='a-icon-text-separator'></i>Last viewed at ${command.lastVisitTime}
									</c:if>
								</div>
								<div class="subHeader" id="taggedKeywords">
									<c:if test="${not empty command.taggedKeywords}">
									<i class='fa fa-tags' style='font-size: 14px; margin-right: 4px;'></i>${command.taggedKeywords}
									</c:if>
								</div>
							</div>
							<div class="entry" id="likeUnike" style="top: 10px;">
								<c:choose>
									<c:when test="${command.likeCount > 1}">
										<span>${command.likeCount} likes</span>
									</c:when>
									<c:otherwise>
										<span>${command.likeCount} like</span>
									</c:otherwise>
								</c:choose>
								<c:if test="${command.blogActive && command.likeAllowed}">
									<c:choose>
										<c:when test="${command.alreadyLike}">
											<i class='a-icon-text-separator'></i><a href="javascript: likeEntry(${command.id}, 0)" class="euInfoSelect" style="font-weight: bold;" >Unlike</a>
										</c:when>
										<c:otherwise>
											<i class='a-icon-text-separator'></i><a href="javascript: likeEntry(${command.id}, 0)" class="euInfoSelect" style="font-weight: bold;" >Like</a>
										</c:otherwise>
									</c:choose>
								</c:if>
							</div>
							<div class="menus">
								<ul style="margin-top: 6px;">
									<c:if test="${command.blogActive && command.addTagAllowed}">
										<li><a class="normalTip" title="Add/Edit tags for this blog entry" onclick="addEditTags('BlogEntry', '${command.id}');" href="javascript:void(0);" 
										>Add/Edit Tags</a></li>
									</c:if>
									<c:if test="${command.blogActive && command.writeAllowed}">
										<li><a class="normalTip" title="Edit this blog entry" href="${communityEraContext.contextUrl}/blog/addEditBlog.do?id=${command.id}&bid=${command.blogId}" 
										>Edit this entry</a></li>
										<li><a class="normalTip" title="Delete this blog entry" onclick="deleteBlogEntry('${command.id}', '');" href="javascript:void(0);" 
										>Delete this entry</a></li>
									</c:if>
									<c:if test="${command.currentUserSubscribed}">
										<li id="subscribeBlogEntry"><a class="normalTip" onclick="unSubscribeBlogEntry(${command.id});" href="javascript:void(0);" 
										title="Unsubcribe from email alerts for this blog entry">Stop Following this Blog Entry</a></li>
									</c:if>
									<c:if test="${not command.currentUserSubscribed}">
										<li id="subscribeBlogEntry"><a class="normalTip" onclick="subscribeBlogEntry(${command.id});" href="javascript:void(0);"  
										title="Get email alerts for this blog entry">Follow this Blog Entry</a></li>
									</c:if>
								</ul>
							</div>
						</div>
						<div class="richtext" style="padding: 10px;">${command.displayBody}</div>	
						<div class='outerBlock' id="showComments">	
							<c:if test="${command.commentCount > 0}">
								<div id="page"></div>
								<div id="waitMessage" style="display: none;">
									<div class="cssload-square" >
										<div class="cssload-square-part cssload-square-green" ></div>
										<div class="cssload-square-part cssload-square-pink" ></div>
										<div class="cssload-square-blend" ></div>
									</div>
								</div>
								<%@ include file="/WEB-INF/jspf/pagination.jspf" %>
								<br />
							</c:if>
							
							<c:if test="${command.blogActive}">
								<div style="margin-top: 30px;" id="addAComment">
									<form:form showFieldErrors="true" commandName="command" name="submitCommentForm">	
										<label for="comment" >Add your comment</label>
										<textarea name='comment' id='comment' style='display:none;'></textarea><div id='editor'></div>
										<c:if test="${command.errorMsg != null}">
											<span class="errorText" style="margin:2px;">${command.errorMsg}</span><br />
										</c:if>
										<form:hidden path="isSubmit" />
										<div class="left" style="margin: 10px 0px;">
											<a href="javascript:void(0);" onclick="submitComment();" class="btnmain" style='float:right;'>Post</a>
										</div>
									</form:form>
								</div><br /><br />
							</c:if>
							<c:if test="${!command.blogActive}">
								<p style="color: #184A72; text-align: center; font-size: 14px;">Blog is not active anymore.</p> 
							</c:if>
						</div>
					</div> 
				</div>
			</div> 
				
			<div class="right-panel" style="margin-top: 0px;">

				<div class="inbox" style="display: inline-block; width: 296px; float: right;">
					<div class="eyebrow">
						<span><i class="fa fa-tags" style="margin-right: 2px;"></i>Popular Tags</span>
					</div>
					<div id="cloud" class="communities"></div>
					<div id="waitCloudMessage" style="display: none;">
						<div class="cssload-square" style="width: 13px; height: 13px;">
							<div class="cssload-square-part cssload-square-green" style="width: 13px; height: 13px;"></div>
							<div class="cssload-square-part cssload-square-pink" style="width: 13px; height: 13px;"></div>
							<div class="cssload-square-blend" style="width: 13px; height: 13px;"></div>
						</div>
					</div>
					<div id="cloudList" style="display: none; " class="communities"></div>
					<ul id="cloudTabs">
						<c:choose>
							<c:when test="${command.toggleList == 'true'}">
								<h3 class="selectedCloudTab" id="hCloud" style="display: none; float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
								<a href="javascript: toggle()" style="float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
								<h3 class="selectedCloudTab" style="float:right;" id="hCloudList">List</h3>
								<a href="javascript: toggle()" id="aCloudList" style="display: none; float:right; color: #66799f;">List</a>
							</c:when>
							<c:otherwise>
								<h3 class="selectedCloudTab" id="hCloud" style="float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
								<a href="javascript: toggle()" style="display: none; float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
								<h3 class="selectedCloudTab" style="display: none; float:right;" id="hCloudList">List</h3>
								<a href="javascript: toggle()" id="aCloudList" style="float:right; color: #66799f;">List</a>
						  	</c:otherwise>
						</c:choose>
					</ul>
				</div>
			</div>
			</div>
		<%@ include file="/WEB-INF/jspf/footer.jspf" %>
		<%@ include file="/WEB-INF/jspf/extraFooter.jspf" %>
	</body>
</html>