<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="/WEB-INF/tlds/cera_form.tld" %> 
<%@ taglib prefix="cera" uri="/WEB-INF/tlds/cera.tld" %> 
 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="author" content="${command.assigner}">
		<meta name="robots" content="index, follow">
		<meta name="google-site-verification" content="JC96M8paj34ChCcPK0EAKWSzDJqocRo6rdSqnzPbIm4" />
		<meta name="description" content="${command.title}. ${command.metaForDescription}" />
		<meta name="keywords" content="Jhapak, Assignments, ToDo community, ${command.keywords}" />
		<title>${command.title} - Jhapak</title>
		<link rel="icon" type="image/png" href="img/link_Image.png"/>
		<link rel="canonical" href="${communityEraContext.requestUrl}" />
		<link rel="publisher" href="https://plus.google.com/+Jhapak4u"/>
		<meta property="article:publisher" content="https://www.facebook.com/EraOfCommunities" />
		
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
  				"@context" : "http://schema.org",
  				"@type" : "Article",
  				"name" : "${command.title}",
  				"author" : {
    				"@type" : "Person",
    				"name" : "${command.assigner}"
  				},
  				"datePublished" : "${command.isoPostedOn}",
				"headline" : "${command.title}",
  				"articleBody" : "${command.metaForDescription}",
  				"url" : "${communityEraContext.requestUrl}"
			}
		</script>
		
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary">
		<meta name="twitter:site" content="@EraCommunity">
		<meta name="twitter:title" content="${command.title}">
		<meta name="twitter:description" content="${command.metaForDescription}">
		<meta name="twitter:url" content="${communityEraContext.requestUrl}">
		
		<!-- Open Graph data -->
		<meta property="og:title" content="${command.title}" />
		<meta property="og:type" content="article" />
		<meta property="og:url" content="${communityEraContext.requestUrl}" />
		<meta property="og:description" content="${command.metaForDescription}" />
		<meta property="og:site_name" content="Jhapak" />
		<meta property="article:published_time" content="${command.isoPostedOn}" />
		<meta property="article:modified_time" content="${command.isoPostedOn}" />

		<meta property="fb:admins" content="100001187666357" /> 
		
		<%@ include file="/WEB-INF/jspf/commHeader.jspf" %>
		<%@ include file="/WEB-INF/jspf/header2.jspf"%>
		<%@ include file="/WEB-INF/jspf/headerTag.jspf"%>
		
		<script type="text/javascript" src="js/qtip/memberInfoTip.js"></script>
		
		<link rel="stylesheet" media="all" type="text/css" href="css/commBnnr.css" />
		<link rel="stylesheet" type="text/css" href="css/allMedia.css" />
		<link rel="stylesheet" type="text/css" href="css/events.css" />
		
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

		<cera:taggingJS context="${communityEraContext}"/>
		<style type="text/css">
			.Zebra_DatePicker {
				z-index: 9999;
			}
			
		 	.login-dialog .modal-dialog {
                width: 500px;
                height:400px;
            }
            
            .response-dialog .modal-dialog {
                width: 720px;
                height:400px;
            }
            
            form label {
            	font-size: 13px;
            }
            a.sublink {
            	position: absolute;
				right: 10px;
				bottom: 12px;
	            float:right;
	            font-size: 12px;
				font-weight: bold;
				color: #66799f;
				text-decoration: none;
            }
            
            a.sublink:hover {
			    color: #2A3A47;
			    text-decoration: none;
			}
			
			#container .left-panel .commSection .paginatedList .details {
			    float: left;
			    width: unset;
			    word-wrap: normal;
			}
			
			.rotateCss {
				-ms-transform: rotate(-45deg); /* IE 9 */
			    -webkit-transform: rotate(-45deg); /* Chrome, Safari, Opera */
			    transform: rotate(-45deg);
			}
			
			div.richtext {
				width: 100%;
			}
			
			.login-dialog .modal-dialog {
            }
            
            .modal-body {
			    padding: 10px;
			}
			
			.modal-footer {
			    padding: 8px;
			    text-align: right;
			    border-top: 1px solid #E5E5E5;
			}
			
			.btn {
				padding: 4px;
			}
			
			.scroll-pane
			{
				height: 430px;
				overflow: auto;
				padding-top: 10px;
			}
			
			.scroll-pane2
			{
				height: 455px;
				overflow: auto;
			}
			
			.jspCap
			{
				display: block;
				background: #eeeef4;
			}
			
			.jspVerticalBar {
			    width: 8px;
			}
			
			.jspVerticalBar .jspCap
			{
				height: 1px;
			}
		 </style>
		 
		<script src="ckeditor/ckeditor.js"></script>
		
		<link rel="stylesheet" href="css/DatePicker/default.css" type="text/css" />
        <link type="text/css" rel="stylesheet" href="css/DatePicker/shCoreDefault.css" />
		
		<link rel="stylesheet" href="css/DatePicker/default.css" type="text/css" />
        <link type="text/css" rel="stylesheet" href="css/DatePicker/shCoreDefault.css" />
        <script type="text/javascript" src="js/DatePicker/XRegExp.js"></script>
        <script type="text/javascript" src="js/DatePicker/shCore.js"></script>
        <script type="text/javascript" src="js/DatePicker/shLegacy.js"></script>
        <script type="text/javascript" src="js/DatePicker/shBrushJScript.js"></script>
        <script type="text/javascript" src="js/DatePicker/shBrushXml.js"></script>        
        <script type="text/javascript" src="js/DatePicker/zebra_datepicker.js"></script>
        <script type="text/javascript" src="js/DatePicker/core.js"></script>
		
		<script type="text/javascript">
			var editor;

			function addAssignmentEntry (rowId, taskId, parentId, isToDo) {
				var tle = "";
				var dd = "";
				if (isToDo == 1) {
					tle = 'Add ToDo item';
					dd= '<div style="float: left; width: 100%; margin-top: 10px;" id="dueDate"><label><strong>Due date</strong></label><br /><div style="float: left; margin-right:6px;">' +
					'<input type="text" style="width: 200px;" class="editInfo" id="datepicker-example1" name="ddate" value="${command.ddate}" placeholder="Due date for assignment" /></div></div>';
				} else {
					tle = 'Add Assignment Entry';
				}
				var mess = '<form id="addAssignmentEntry"><input type="hidden" id="taskId" name="taskId"/><input type="hidden" name="parentId" id="parentId"/><input type="hidden" name="entryType" id="entryType"/>' +
				'<label for="title">Title (100 characters max.)</label><br /><input id="title" name="title" maxlength="100" style="width: 99%;"/><br />' +
				'<label for="description">Description</label><br/><textarea name="description" id="description" style="display:none;"></textarea><div id="editor"></div>' + dd +
				'<br /><label for="txtKeywords" >Add Tags</label><input id="addedTags" name="tags" type="text" class="tagFieldInput" autocomplete="off" style="width: 99%;"></input></form>';
				
				var type = BootstrapDialog.TYPE_INFO;
				BootstrapDialog.show({
	                type: type,
	                title: tle,
	                message: mess,
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
		                label: 'Cancel',
		                action: function(dialog){
		            	dialog.close();
	                }
		            }, {
		                label: 'Submit',
		                cssClass: 'btn-primary',
		                action: function(dialog) {
		            	var body = editor.getData();
		            	dialog.getModalBody().find('#description').val(body);
		            	dialog.getModalBody().find('#taskId').val(taskId);
		            	dialog.getModalBody().find('#parentId').val(parentId);
		            	dialog.getModalBody().find('#entryType').val(isToDo);
		            	
		            	$.ajax({
		            	     type: "POST",
		            		 url: "${communityEraContext.currentCommunityUrl}/assignment/addAssignment.ajx",
		            		 data: dialog.getModalBody().find('#addAssignmentEntry').serialize(),
		            		 dataType: "json",
		            	     success: function(msg){
			            			 var currentUser = document.getElementById('currentUser').value;
			            			 var entryCount = document.getElementById('entryCount').value;
			            			 
			            			 var sName = "<div class='paginatedList' id='resp-div-"+msg.entryId+"' style='margin-left:"+msg.level*20+"px; padding: 0px;'>";
			            			 sName += "<a name='A$"+msg.entryId+"'></a><div style='padding: 10px;'><div class='leftImg'>";
			            			 if(msg.photoPresent){
										 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+msg.posterId+"&backlink=ref' ><img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+msg.posterId+"' alt="+msg.posterName+" style='width: 35px; height: 35px;' /></a>"; }
									 else {
										 sName += "<img src='img/user_icon.png' style='width: 35px; height: 35px;' />";
									 }
		
									 sName += "</div><div class='details' style='margin-bottom: 4px;'>";
									 sName += "<div class='heading' style='margin-bottom: 4px;'><span style='color: #184A72; font-size: 14px;' id='respSubject-"+msg.entryId+"'>"+msg.title+"</span><br/></div>";
									 
									 sName += "<div class='person' style='font-size: 14px;'>Created by <a href='${communityEraContext.contextUrl}/pers/connectionResult.do?backlink=ref&amp;id="+msg.posterId+"' >"+msg.posterName+"</a>";
									 if(isToDo == 1){
									 	sName += " <i class='a-icon-text-separator'></i><span title='"+msg.postedOnHover+"'>"+msg.postedOn+"</span>";
									 }
									 if(msg.posterId == currentUser){
										 sName += "<i class='a-icon-text-separator'></i><a href='javascript:void(0);' onclick='editEntry(&#39;"+msg.entryId+"&#39;, &#39;"+isToDo+"&#39;);' >Edit</a>";
									 }
									 sName += "</div></div>";
									 sName += "<div class='richtext' style='float: right;' id='body-"+msg.entryId+"'>"+msg.body+"</div></div>";
		
									 sName += "<div class='topSection' style='border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;'><div><ul class='bottSecLst'>";

									 sName += "<li style='float: right; margin: 2px;'><a href='javascript:void(0);' onclick='addAssignmentEntry(&#39;"+msg.entryId+"&#39;, &#39;"+taskId+"&#39;, &#39;"+msg.entryId+"&#39;, &#39;1&#39;);' class='btnmain' style='height: 22px; line-height: 16px;'>";
									 sName += "<i class='fa fa-tasks' style='margin-right: 4px;'></i>Add ToDo Item</a></li>";
									 sName += "<li style='float: right; margin: 2px;'><a href='javascript:void(0);' onclick='addAssignmentEntry(&#39;"+msg.entryId+"&#39;, &#39;"+taskId+"&#39;, &#39;"+msg.entryId+"&#39;, &#39;0&#39;);' class='btnmain' style='height: 26px; line-height: 22px;'>";
									 sName += "<i class='fa fa-th-list' style='margin-right: 4px;'></i>Add Entry</a></li>";

									 sName += "</ul></div></div></div>";
									 var divId = "#assignmentDiv";
									 if (entryCount > 0) {
										divId = "#resp-div-"+msg.lastSiblingId;
									 }
								 
								 $(sName).insertAfter(divId);
								 $("#waitMessage").hide();
								 dialog.close();
							    	},
						         beforeSend: function () {
						             $("#waitMessage").show();
						         } 
		            	       });
		            	
		            	}
		            }],
	                cssClass: 'response-dialog',
	                onshown: function(dialogRef){
						var config = {};
						editor = CKEDITOR.appendTo( 'editor', config );
						if (isToDo == 1) {
							$('#datepicker-example1').Zebra_DatePicker();
						}
				}
	            });
			}

			function editAssignment(entryId){
				var isAuthenticated = $("#isAuthenticated").val();
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in. Please login first to edit. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }],
		                cssClass: 'login-dialog'
		            });
			    } else {
				var mess = '<form id="submitAssignmentEntry" style="display: inline-block;"><input type="hidden" id="id" name="id"/>' +
				'<label for="title">Title (100 characters max.)</label><br /><input id="title" name="title" maxlength="100" style="width: 664px;"/><br /><br />' +
				'<label for="entry">Description</label><br/><div id="waitMessage" style="display: none;"><p class="showWaitMessage"></p></div><textarea name="body" id="body" style="display:none;"></textarea><div id="editor"></div>'+
				'<div style="float: left; width: 100%; margin-top: 10px;" id="dueDate"><label><strong>Due date</strong></label><br /><div style="float: left; margin-right:6px;">' +
				'<input type="text" style="width: 200px;" class="editInfo" id="datepicker-example1" name="ddate" value="${command.ddate}" placeholder="Due date for assignment" /></div></div>' +
				'<br /></form>';
				
				var type = BootstrapDialog.TYPE_INFO;
				BootstrapDialog.show({
	                type: type,
	                title: 'Edit Assignment',
	                message: mess,
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
		                label: 'Cancel',
		                action: function(dialog){
		            	dialog.close();
	                }
		            }, {
		                label: 'Submit',
		                cssClass: 'btn-primary',
		                action: function(dialog) {
		            	var body = editor.getData();
		            	dialog.getModalBody().find('#body').val(body);
		            	dialog.getModalBody().find('#id').val(entryId);
		            	$.ajax({
		            	     type: "POST",
		            		 url: "${communityEraContext.currentCommunityUrl}/assignment/editAssignment.ajx",
		            		 data: dialog.getModalBody().find('#submitAssignmentEntry').serialize(),
		            		 dataType: "json",
		            	         success: function(msg){
		            			 
		            			 $("#taskSubject").html(dialog.getModalBody().find('#title').val());
		     					$("#taskBody").html(body);

								 
								 $("#waitMessage").hide();
								 dialog.close();
							    	},
						         beforeSend: function () {
						             $("#waitMessage").show();
						         } 
		            	       });
		            	
		            	}
		            }],
	                cssClass: 'response-dialog',
	                onshown: function(dialogRef){
					//subject
					var respTitle = $("#taskSubject").html();
					$("#title").val(respTitle);
					var quote = $("#taskBody").html();
					var config = {};
					editor = CKEDITOR.appendTo( 'editor', config, quote );
					
					$('#datepicker-example1').Zebra_DatePicker();
					
					}
	            });

			    }
			}

			function editEntry(entryId, isToDo){
				var isAuthenticated = $("#isAuthenticated").val();
				
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in. Please login first to edit. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }],
		                cssClass: 'login-dialog'
		            });
			    } else {
			    	var tle = "";
					var dd = "";
					if (isToDo == 1) {
						tle = 'Edit ToDo item';
						dd= '<div style="float: left; width: 100%; margin-top: 10px;" id="dueDate"><label><strong>Due date</strong></label><br /><div style="float: left; margin-right:6px;">' +
						'<input type="text" style="width: 200px;" class="editInfo" id="datepicker-example1" name="ddate" value="${command.ddate}" placeholder="Due date for assignment" /></div></div>';
					} else {
						tle = 'Edit Assignment Entry';
					}
			    				    
				var mess = '<form id="submitAssignmentEntry" style="display: inline-block;"><input type="hidden" id="id" name="id"/>' +
				'<label for="title">Title (100 characters max.)</label><br /><input id="title" name="title" maxlength="100" style="width: 664px;"/><br /><br />' +
				'<label for="entry">Description</label><br/><div id="waitMessage" style="display: none;"><p class="showWaitMessage"></p></div><textarea name="body" id="body" style="display:none;"></textarea><div id="editor"></div>'+dd+'<br /></form>';
				
				var type = BootstrapDialog.TYPE_INFO;
				BootstrapDialog.show({
	                type: type,
	                title: tle,
	                message: mess,
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
		                label: 'Cancel',
		                action: function(dialog){
		            	dialog.close();
	                }
		            }, {
		                label: 'Submit',
		                cssClass: 'btn-primary',
		                action: function(dialog) {
		            	var body = editor.getData();
		            	dialog.getModalBody().find('#body').val(body);
		            	dialog.getModalBody().find('#id').val(entryId);
		            	$.ajax({
		            	     type: "POST",
		            		 url: "${communityEraContext.currentCommunityUrl}/assignment/editAssignment.ajx",
		            		 data: dialog.getModalBody().find('#submitAssignmentEntry').serialize(),
		            		 dataType: "json",
		            	         success: function(msg){
		            			 
		            			 $("#respSubject-"+entryId).html(dialog.getModalBody().find('#title').val());
		     					$("#body-"+entryId).html(body);

								 
								 $("#waitMessage").hide();
								 dialog.close();
							    	},
						         beforeSend: function () {
						             $("#waitMessage").show();
						         } 
		            	       });
		            	
		            	}
		            }],
	                cssClass: 'response-dialog',
	                onshown: function(dialogRef){
					//subject
					var respTitle = $("#respSubject-"+entryId).html();
					$("#title").val(respTitle);
					var quote = $("#body-"+entryId).html();
					var config = {};
					editor = CKEDITOR.appendTo( 'editor', config, quote );
					if (isToDo == 1) {
						$('#datepicker-example1').Zebra_DatePicker();
					}
				}
	            });

			    }
			}
			
			function showAssignedTo(entryId) 
			{ 
				var pfcnt = $("#pgCountAssigned"+entryId).val();
				if (pfcnt != -1) {
					showAssignee(entryId);
				}
			}

			function showAssignee(entryId) 
			{ 
				$.ajax({url:"${communityEraContext.contextUrl}/assignment/showAssignee.ajx?entryId="+entryId,success:function(result){
					var sName = "";
					$.each(result.bData, function() {
						 sName += "<div class='content' style='float: left; margin: 2px;'>";
						 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+this['userId']+"' class='memberInfo name' ";
						 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+this['userId']+"'>";
						 if(this['photoPresent']){
						 	sName += " <img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+this['userId']+"' width='43' height='43' style='padding: 0px 0px 3px 0px;' />";
						 } else {
							 sName += "<img src='img/user_icon.png' width='43' height='43' style='padding: 0px 0px 3px 0px;' />";
						 }
						 sName += "</a></div>";
						 		
					 });
					$("#waitMessageAsignee"+entryId).hide();
					 $("#outerAsigneeLst-"+entryId).html(sName);
					 memberInfoQtip();
		    	  },
				 	// What to do before starting
			         beforeSend: function () {
			             $("#assigneeSec-"+entryId).show();
			             $("#waitMessageAsignee"+entryId).show();
			         } 
		    	  });
			}

			function addAssignee(entryId, communityId) {
				var dialogInstance = BootstrapDialog.show({
					title: 'Assigned To',
					message: function(dialog) {
					var $message = $('<div id="main"><p id="waitCloudMessage" style="margin-left: 240px; margin-top: 180px; min-height:250px; display: none;" class="showCloudWaitMessage" ></p></div>');
	                return $message;
	            },
	            buttons: [{
	                label: 'Cancel',
	                action: function(dialog){
	            	dialog.close();
                }
	            }, {
	                label: 'Save',
	                cssClass: 'btn-primary',
	                action: function(dialog) {
	                var flist = $( ".clearfix2" ).map(function() {return this.id;}).get().join();
	                    processSave(flist, entryId);
	                    dialog.close();
	                }
	            }],
	            cssClass: 'login-dialog',
	            onshown: function(dialogRef){
					$.ajax({url:"${communityEraContext.contextUrl}/assignment/makeAssigneeList.ajx?communityId="+communityId ,dataType: "json",success:function(result){
						var stoggle = "";
						var sName = "<div style='overflow: hidden;'><div class='finallist' style='padding-right: 7px; width: 46%;'><div style='padding:10px;'>Final list</div><div id='scrollpane' class='scroll-pane2'><form id='formset' method='post' action=''></form></div>";
						sName += "</div><div>";						
						
						var temp = "";
						var counter = 0;
						$.each(result.bData, function() {
							counter += 1;
							var rid = this['userId'];
							stoggle += rid + "#" + this['photoPresent'] + "#" +this['name']+ ",";
							temp += "<li class='lientry'><div class='clearfix' id='"+rid+"' onclick='expand(&#39;"+rid+"&#39;, &#39;"+this['photoPresent']+"&#39; , &#39;"+this['name']+"&#39;)'>";

							if(this['photoPresent']){
								temp += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+this['userId']+"' />"; }
							 else {
								 temp += "<img src='img/user_icon.png' />";
							 }
							temp += "<span id='selection-"+rid+"' class='selection'></span><div class='header'>"+this['name']+"</div><div class='loc'></div></div></li>";
							});

						sName += "<div class='rev' style='float: left; width: 46%;'><div class='clearfix'><div class='tohele'>Assigned To ("+counter+")</div><div class='toheri'><a href='javascript:void(0);' onclick='toggleSelect(&#39;0&#39;,&#39;"+stoggle+"&#39;, &#39;"+entryId+"&#39;);'>Select All</a></div></div><div class='scroll-pane horizontal-only'><ul>";
						sName += temp;
						sName += "</ul></div></div>";

						
						sName += "</div></div>";
						sName += "</div>";
						
						 dialogRef.getModalBody().find('#main').html(sName);
						// var ii = 8;
	                	// Hide message
	    		        dialogRef.getModalBody().find('#waitCloudMessage').hide();
		    		       // if(ii > 8){
	    		        dialogRef.getModalBody().find('.scroll-pane').jScrollPane(
	    		        		{
	    		        			verticalDragMinHeight: 20,
	    		        			verticalDragMaxHeight: 200,
	    		        			autoReinitialise: true
	    		        			}
	    	    		        );
	    		        dialogRef.getModalBody().find('.scroll-pane2').jScrollPane(
	    		        		{
	    		        			verticalDragMinHeight: 20,
	    		        			verticalDragMaxHeight: 200,
	    		        			autoReinitialise: true
	    		        			}
	    	    		        );
	    		       // }
	    		        $.each(result.bData, function() {
		    		        var id = this['userId'];
		    		        var photoPresent = this['photoPresent'];
		    		        var name = this['name'];
	    		        	var fset = document.getElementById('formset');
	    					var spanTag = document.getElementById('selection-'+id);
	    					var ss = id+"#"+photoPresent+"#"+name;
	    					if (this['assigned'] == 1) {
	    						spanTag.className = 'selection2';
	    						var tag = "<div class='clearfix2' id='"+ss+"' onclick='rmFlist(&#39;"+id+"&#39;, &#39;"+ss+"&#39;)'>";
	     					   if(photoPresent){
	     						   tag += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+id+"' width='30' height='30' style='float: left;'/>"; }
	     						 else {
	     							 tag += "<img src='img/user_icon.png'  width='30' height='30' style='float: left;'/>";
	     						 }
	     					   tag += "<span id='finalSelection-"+id+"' class='selection3'></span><div class='header2'>"+name+"</div></div>";
	     					   document.getElementById('formset').innerHTML += tag;
							} else {
								spanTag.className = 'selection';
							}
    					   
    					   dialogRef.getModalBody().find('.scroll-pane').jScrollPane(
   	    		        		{
   	    		        			verticalDragMinHeight: 20,
   	    		        			verticalDragMaxHeight: 200,
   	    		        			autoReinitialise: true
   	    		        			}
   	    	    		        );
    					   dialogRef.getModalBody().find('.scroll-pane2').jScrollPane(
      	    		        		{
      	    		        			verticalDragMinHeight: 20,
      	    		        			verticalDragMaxHeight: 200,
      	    		        			autoReinitialise: true
      	    		        			}
      	    	    		        );
	    		        });
						
	    			    },
	    			 	// What to do before starting
	    		         beforeSend: function () {
	    			    	dialogRef.getModalBody().find('#waitCloudMessage').show();
	    		         } 
	    		    });
	            }
		        });
			}

			function processSave(ids, entryId){
				var invtList = document.getElementById('outerAsigneeLst-'+entryId);
				var fset = document.getElementById('finalList');
				if (ids != "") {
					var array = ids.split(',');
					if (array.length > 0){
						var tag = "";
						var temp ="";
						for(var x=0; x < array.length ;x++){
							var inner = array[x];
							var innerArray = inner.split('#');
							var spanTag = document.getElementById('selection-'+innerArray[0]);
							if (x < 15) {
							   if(innerArray[1]){
								   tag += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+innerArray[0]+"&backlink=ref' title='"+innerArray[2]+"' >";
								   tag += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+innerArray[0]+"'  width='43' height='43' style='float: left;padding: 0px 3px 3px 0px;'/></a>"; 
								   } else {
									   tag += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+innerArray[0]+"&backlink=ref' onmouseover='"+${row.firstName} ${row.lastName}+"' >";
									   tag += "<img src='img/user_icon.png'  width='43' height='43' style='float: left;padding: 0px 3px 3px 0px;'/></a>"; 
								 }
							}
							temp += innerArray[0]+",";
						}
						var fc = invtList.firstChild;
						while( fc ) {
							invtList.removeChild( fc );
						    fc = invtList.firstChild;
						}
						invtList.innerHTML += tag;
						fset.value = temp;
					}
				} else {
					var fc2 = invtList.firstChild;
					while( fc2 ) {
						invtList.removeChild( fc2 );
					    fc2 = invtList.firstChild;
					}
					fset.value = ids;
				}

				var comment = $("#intComm"+entryId).val();

				$.ajax({type:"POST",url:"${communityEraContext.contextUrl}/assignment/addAssignee.ajx?entryId="+entryId,data:{assignees:temp},success:function(result){
					 var sName = "";
					 sName += "<li class='commentEntity'><div class='content'>";
					 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+result.posterId+"' class='memberInfo actorImage' ";
					 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+result.posterId+"'>";
					 if(result.photoPresent){
					 	sName += " <img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+result.posterId+"' />";
					 } else {
						 sName += "<img src='img/user_icon.png' />";
					 }
					 sName += "</a></div>";
					 sName += "<div class='header'><h4 class='subHeadline'><a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+result.posterId+"' class='memberInfo name' ";
					 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+result.posterId+"'>"+result.posterName+"</a>";
					 sName += "<span class='textEntity'>"+result.comment+"</span>";

					 sName += "<div class='commLike'>"+result.datePosted+"</div>";

					 sName += "</h4></div></li>";
					 
					 $("#commentList-"+entryId).append(sName);
					 memberInfoQtip();
					 $("#intComm"+entryId).val("");
					 $("#addc"+entryId).removeClass("enabled");
		    	  },
				 	// What to do before starting
			         beforeSend: function () {
			         } 
		    	  });
				
			}

			function expand(id, photoPresent, name){
				
				var fset = document.getElementById('formset');
				var spanTag = document.getElementById('selection-'+id);
				var ss = id+"#"+photoPresent+"#"+name;
			   if(spanTag.className == "selection") {
				   if (spanTag.parentNode != fset){
				   spanTag.className = 'selection2';
				   
				   var tag = "<div class='clearfix2' id='"+ss+"' onclick='rmFlist(&#39;"+id+"&#39;, &#39;"+ss+"&#39;)'>";
				   if(photoPresent){
					   tag += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+id+"'  width='30' height='30' style='float: left;'/>"; }
					 else {
						 tag += "<img src='img/user_icon.png'  width='30' height='30' style='float: left;'/>";
					 }
				   tag += "<span id='finalSelection-"+id+"' class='selection3'></span><div class='header2'>"+name+"</div></div>";
				   document.getElementById('formset').innerHTML += tag;
				   }
			   } else {
				   spanTag.className = 'selection';
				   fset.removeChild(document.getElementById(ss));
			   }

			   $('#scrollpane').jScrollPane(
		        		{
		        			verticalDragMinHeight: 20,
		        			verticalDragMaxHeight: 200,
		        			autoReinitialise: true
		        			}
	    		        );
			}

			function rmFlist(id, fid){
				var fset = document.getElementById('formset');
				fset.removeChild(document.getElementById(fid));
				var spanTag = document.getElementById('selection-'+id);
				spanTag.className = 'selection';
			}

			function toggleSelect(isAllSelect, ids, entryId) {
				var array = ids.split(',');
				var invtList = document.getElementById('outerAsigneeLst-'+entryId);
				var fset = document.getElementById('formset');
				if (array.length > 0) {
					
				for ( var x = 0; x < array.length; x++) {
					var tag = "";
					var ss = array[x];
					var innerArray = ss.split('#');
					var spanTagleft = document.getElementById('selection-' + innerArray[0]);
					var spanTagright = document.getElementById('finalSelection-' + innerArray[0]);
					
					spanTagleft.className = 'selection2';
					if (!spanTagright) {
						tag += "<div class='clearfix2' id='" + ss
								+ "' onclick='rmFlist(&#39;" + innerArray[0] + "&#39;, &#39;"
								+ ss + "&#39;)'>";
						if (innerArray[1]) {
							tag += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="
									+ innerArray[0]
									+ "'  width='30' height='30' style='float: left;'/>";
						} else {
							tag += "<img src='img/user_icon.png'  width='30' height='30' style='float: left;'/>";
						}
						tag += "<span id='finalSelection-"
								+ innerArray[0]
								+ "' class='selection3'></span><div class='header2'>"
								+ innerArray[2] + "</div></div>";
						document.getElementById('formset').innerHTML += tag;
						}
					}
				}
			}

			function showCommentsTop(entryId) 
			{ 
				var pfcnt = $("#pgCount"+entryId).val();
				if (pfcnt != -1) {
					showComments(entryId);
				}
			}

			function showComments(entryId) 
			{ 
				var pfcnt = $("#pgCount"+entryId).val();
				$.ajax({url:"${communityEraContext.contextUrl}/assignment/showComments.ajx?jPage="+pfcnt+"&entryId="+entryId,success:function(result){
					var fList = "";
					var rowCnt = result.rowCnt;
					var pgCnt = result.pgCnt;
					var nxtPage = result.nxtPage;

					if (nxtPage <= pgCnt) {
						$("#pgCount"+entryId).val(nxtPage);
					} else {
						$("#spc"+entryId).hide();
						$("#pgCount"+entryId).val(-1);
					}
					$.each(result.aData, function() {
						var sName = "";
						 sName += "<li class='commentEntity'><div class='content'>";
						 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+this['posterId']+"' class='memberInfo actorImage' ";
						 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+this['posterId']+"'>";
						 if(this['photoPresent']){
						 	sName += " <img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+this['posterId']+"' />";
						 } else {
							 sName += "<img src='img/user_icon.png' />";
						 }
						 sName += "</a></div>";
						 sName += "<div class='header'><h4 class='subHeadline'><a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+this['posterId']+"' class='memberInfo name' ";
						 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+this['posterId']+"'>"+this['firstName']+ " " + this['lastName']+"</a>";
						 sName += "<span class='textEntity'>"+this['commentToDisplay']+"</span>";

						 sName += "<div class='commLike'>"+this['datePostedOn']+"</div>";

						 sName += "</h4></div></li>";
						 		
						 fList = sName + fList;
					 });
					$("#waitMessage"+entryId).hide();
					 $("#commentList-"+entryId).prepend(fList);
					 memberInfoQtip();
		    	  },
				 	// What to do before starting
			         beforeSend: function () {
			             $("#commentSec-"+entryId).show();
			             $("#waitMessage"+entryId).show();
			         } 
		    	  });
			}

			function toggleBtn(entryId) 
			{ 
				var textA = $("#intComm"+entryId).val();
				if (textA == "") {
					$("#addc"+entryId).removeClass("enabled")
				} else {
					$("#addc"+entryId).addClass("enabled");

				}
			}

			function addComments(entryId) 
			{ 
				var comment = $("#intComm"+entryId).val();
				if (comment == "") {
					$("#addc"+entryId).removeClass("enabled");
				} else {
					$.ajax({type:"POST",url:"${communityEraContext.contextUrl}/assignment/addComments.ajx?entryId="+entryId,data:{comment:comment},success:function(result){
						 var sName = "";
						 sName += "<li class='commentEntity'><div class='content'>";
						 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+result.posterId+"' class='memberInfo actorImage' ";
						 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+result.posterId+"'>";
						 if(result.photoPresent){
						 	sName += " <img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+result.posterId+"' />";
						 } else {
							 sName += "<img src='img/user_icon.png' />";
						 }
						 sName += "</a></div>";
						 sName += "<div class='header'><h4 class='subHeadline'><a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+result.posterId+"' class='memberInfo name' ";
						 sName += " title='${communityEraContext.contextUrl}/pers/connectionInfo.do?id="+result.posterId+"'>"+result.posterName+"</a>";
						 sName += "<span class='textEntity'>"+result.comment+"</span>";

						 sName += "<div class='commLike'>"+result.datePosted+"</div>";

						 sName += "</h4></div></li>";
						 
						 $("#commentList-"+entryId).append(sName);
						 memberInfoQtip();
						 $("#intComm"+entryId).val("");
						 $("#addc"+entryId).removeClass("enabled");
			    	  },
					 	// What to do before starting
				         beforeSend: function () {
				         } 
			    	  });

				}
			}
			
			$(document).ready(function () {
				hljs.initHighlightingOnLoad();
			});
		</script>
	</head>

	<body id="communityEra">
		<%@ include file="/WEB-INF/jspf/topHeader.jspf" %>
		<div class="commBanr">
			<div class="bnrImg" style="background-image:url(${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&imgType=Banner&communityId=${communityEraContext.currentCommunity.id});" >
				<div class="innerPanl">
					<div class="carousel_caption">
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Private'}">
							<h4><i class="fa fa-lock" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Protected'}">
							<h4><i class="fa fa-shield" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Public'}">
							<h4><i class="fa fa-globe" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<p>${communityEraContext.currentCommunity.welcomeText}</p>							
					</div>
					
					<div class="menuContainer">
						<ul id="gn-menu" class="gn-menu-main">
							<li><a href="${communityEraContext.currentCommunityUrl}/assignment/showAssignments.do"><i class="fa fa-briefcase" style="margin-right: 8px;"></i>Assignments</a></li>
							<li>
								<nav id="menu">
						    		<input type="checkbox" id="toggle-nav"/>
						    		<label id="toggle-nav-label" for="toggle-nav"><i class="fa fa-bars"></i></label>
						    		<div class="box">
							    		<ul>
							    			<li><a href="${communityEraContext.currentCommunityUrl}/home.do"><i class="fa fa-home" style="margin-right: 8px;"></i>Home</a></li>
							    			<c:forEach items="${communityEraContext.enabledFeatureNamesForCurrentCommunity}" var="feature">
												<c:if test="${feature == 'Blog'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/blog/viewBlog.do"><i class="fa fa-quote-left" style="margin-right: 8px;"></i>Blogs</a></li>
												</c:if>
												<c:if test="${feature == 'Forum'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/forum/showTopics.do"><i class="fa fa-comments-o" style="margin-right: 8px;"></i>Forums</a></li>
												</c:if>
												<c:if test="${feature == 'Wiki'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/wiki/showWikiEntries.do"><i class="fa fa-book" style="margin-right: 8px;"></i>Wikis</a></li>
												</c:if>
												<c:if test="${feature == 'Members'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/connections/showConnections.do"><i class="fa fa-user-plus" style="margin-right: 8px;"></i>Members</a></li>
												</c:if>
												<c:if test="${feature == 'Library'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/library/showLibraryItems.do"><i class="fa fa-folder-open" style="margin-right: 8px;"></i>Library</a></li>
												</c:if>
												<c:if test="${feature == 'Events'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/event/showEvents.do"><i class="fa fa-calendar-check-o" style="margin-right: 8px;"></i>Events</a></li>
												</c:if>
											</c:forEach>
							    		</ul>
						    		</div>
						    	</nav>
					    	</li>
						</ul>
					</div><!-- /container -->
						
					<div class="groups">
						<div class="picture">
							<c:choose>
								<c:when test="${communityEraContext.currentCommunity.logoPresent}">		
									<img src="${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&communityId=${communityEraContext.currentCommunity.id}" width="290" height="290" /> 
								</c:when>
								<c:otherwise>
									<img src="img/community_Image.png" id="photoImg" width="290" height="290" />
								</c:otherwise>
							</c:choose>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="container">
			<div class="left-panel">
				<input type="hidden" id="isAuthenticated" name="isAuthenticated" value="${communityEraContext.userAuthenticated}" />
				<input type="hidden" id="currentUser" value="${communityEraContext.currentUser.id}" />
				<input type="hidden" id="entryCount" value="${command.entryCount}" />
				<input id="finalList" type="hidden" name="finalList" />
				
				<div class="commSection">
					<div class="paginatedList" style="padding: 0px; margin: 0px 0PX 10px auto;" id="assignmentDiv">
						<a name="A${command.id}"></a>
						<div class="topSection" >
							<div class="leftImg">							
								<c:choose>
									<c:when test="${command.photoPresent == 'Y'}">						 
										 <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.creatorId}&backlink=ref">
										 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.creatorId}"/></a>
									</c:when>
									<c:otherwise>
										<img src="img/user_icon.png" />
									</c:otherwise>
								</c:choose>
							</div>
							<div class="topHeader" >
								<div class="heading" style="width: 600px; color: #184A72; margin-bottom: 2px;">
									<span style="font-size: 20px; font-weight: bold;" id="taskSubject">${command.title}</span>
								</div>
								<div class="subHeader">
									Created by 
									<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.creatorId}&backlink=ref" class='memberInfo'
									title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.creatorId}" >${command.assigner}</a>
									<i class='a-icon-text-separator'></i><span title="${command.postedOnHover}">${command.postedOn}</span>
									<i class='a-icon-text-separator'></i>
									<c:choose>
										<c:when test="${command.passedDue}">						 
											<span style="color: red;" title="${command.dueOnHover}">Due ${command.dueOn}</span>
										</c:when>
										<c:otherwise>
											<span style="color: green;" title="${command.dueOnHover}">Due ${command.dueOn}</span>
										</c:otherwise>
									</c:choose>
								</div>
								<c:if test="${not empty command.taggedKeywords}">
									<div class="subHeader">
										<i class='fa fa-tags' style='font-size: 14px; margin-right: 4px;'></i>${command.taggedKeywords}
									</div>
								</c:if>
							</div> 
							<%--<div class='entry' style="color: #999; top: 10px; right: 10px;">#1</div> --%>
							<div class="menus">
								<ul style="margin-top: 6px;">
									<c:if test="${command.creatorId == communityEraContext.currentUser.id }">
										<li><a href="javascript:void(0);" onclick="editAssignment(${command.id})"><i class='fa fa-pencil' style='margin: 0px 4px; font-size: 14px;'></i>Edit</a></li>
									</c:if>
									<li><a href="javascript:void(0);" onclick="addAssignmentEntry(${command.id}, ${command.id}, 0, 0)"><i class='fa fa-flag' style='margin: 0px 4px; font-size: 14px;'></i>Add Entry</a></li>
									<li><a href="javascript:void(0);" onclick="addAssignmentEntry(${command.id}, ${command.id}, 0, 1)"><i class='fa fa-tasks' style='margin: 0px 4px; font-size: 14px;'></i>Add ToDo Item</a></li>
								</ul>
							</div>
						</div>
						
						<div class="inboxAds">
							<c:if test="${communityEraContext.production}">
								<!-- CERA_RES -->
								<ins class="adsbygoogle"
								     style="display:block"
								     data-ad-client="ca-pub-8702017865901113"
								     data-ad-slot="3781277785"
								     data-ad-format="auto"></ins>
								<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
								</script>
							</c:if>
						</div>
						<div class="richtext" style="float: left; width: 98%; margin-bottom:10px; padding: 10px;" id="taskBody">${command.displayBody}</div>
					</div>
					
					<c:set var="flag" value="0"/>
					<c:forEach items="${command.items}" var="row" varStatus="status">
						<a name="A${row.id}"></a><div class="paginatedList" style="margin-left:${row.level*20}px; padding: 0px;" id="resp-div-${row.id}">
							
							<div style='padding: 10px;'>
								<div class='leftImg'>
									<c:choose>
										<c:when test="${row.entryType == 1}">	
											<i class='fa fa-tasks' style='margin: 0px 4px; font-size: 14px;'></i>	
										</c:when>
										<c:otherwise>
											<i class='fa fa-flag' style='margin: 0px 4px; font-size: 14px;'></i>
										</c:otherwise>
									</c:choose> 
								</div>
								<div class="details" style="margin-bottom: 4px;">
									<c:if test="${not empty row.title}">
										<div class="heading">
											<span style='color: #184A72; font-size: 14px;' id='respSubject-${row.id}'>${row.title}</span><br/>
										</div>
									</c:if>
									<div class="person" style="font-size: 14px;">
										Created by <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?backlink=ref&amp;id=${row.creatorId}" >${row.creatorName}</a> <i class='a-icon-text-separator'></i> ${row.postedOn}
										<c:if test="${row.entryType == 1}">
											<i class='a-icon-text-separator'></i>
											<c:choose>
												<c:when test="${row.passedDue}">						 
													<span style="color: red;" title="${row.dueOnHover}">Due ${row.dueOn}</span>
												</c:when>
												<c:otherwise>
													<span style="color: green;" title="${row.dueOnHover}">Due ${row.dueOn}</span>
												</c:otherwise>
											</c:choose>
										</c:if>
										<c:if test="${row.creatorId == communityEraContext.currentUser.id }">
											<i class='a-icon-text-separator'></i><a href="javascript:void(0);" onclick="editEntry(${row.id}, ${row.entryType});">Edit</a>
										</c:if>
									</div>
								</div>
								<%--<div class='entry' style="font-size: 12px; color: #999; top: 10px; right: 10px; float: right;" >#${status.index+2}</div> --%>
								<div class="richtext" style="float: right;" id="body-${row.id}">${row.body}</div>
							</div>
							<div class="topSection" style="border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;">
								<div>
									<ul class="bottSecLst">
										<li style="margin: 2px;">
											<a href='javascript:void(0);' onclick='showCommentsTop(&#39;${row.id}&#39;);' class='lkBtn'>Comment</a>
										</li>
										<li style="margin: 2px 2px 2px 20px;">
											<a href='javascript:void(0);' onclick='showAssignedTo(&#39;${row.id}&#39;);' class='lkBtn'>Assigned to</a>
										</li>
										<c:if test="${row.level < 3}">
											<li style="float: right; margin: 2px;">
												<a href="javascript:void(0);" onclick="addAssignmentEntry('${row.id}', '${row.taskId}', '${row.id}', '1');" class="btnmain" style="height: 22px; line-height: 16px; font-size: 13px;  font-weight: normal;"><i class='fa fa-tasks' style='margin: 0px 4px; font-size: 13px;'></i>Add ToDo</a>
											</li>
											<c:if test="${row.entryType == 0}">
												<li style="float: right; margin: 2px;">
													<a href="javascript:void(0);" onclick="addAssignmentEntry('${row.id}', '${row.taskId}', '${row.id}', '0');" class="btnmain" style="height: 22px; line-height: 16px; font-size: 13px;   font-weight: normal;"><i class='fa fa-flag' style='margin: 0px 4px; font-size: 13px;'></i>Add Entry</a>
												</li>
											</c:if>
										</c:if>
									</ul>
								</div>
								<div class='commentSec' id='commentSec-${row.id}' style="display: none;">
						 				<c:if test="${row.id > 3}">
						 					<a href='javascript:void(0);' onclick='showComments(&#39;${row.id}&#39;);' 
						 						id='spc${row.id}' class='lkBtn'>Show previous comments</a>
						 				</c:if>
						 				<input type="hidden" id="pgCount${row.id}" value="0" />
						 				<div id="waitMessage${row.id}" style="display: none;">
						 					<div class="cssload-square" >
												<div class="cssload-square-part cssload-square-green" ></div>
												<div class="cssload-square-part cssload-square-pink" ></div>
												<div class="cssload-square-blend" ></div>
											</div>
						 				</div>
						 				<div class='commentList'>
						 					<ul id='commentList-${row.id}'>
						 					</ul>
						 				</div>
						 				<div class='addCommForm'>
											<textarea id='intComm${row.id}' placeholder='Add a comment...' cols='60' rows='1' class='edit' onkeyup='toggleBtn(&#39;${row.id}&#39;);'></textarea>
											<div class='buttonContainer'>
												<a href='javascript:void(0);' onclick='addComments(&#39;${row.id}&#39;);' 
						 							id='addc${row.id}' class='commentSubmit'>Comment</a>
											</div>
										</div>
									</div>
									<div class='commentSec' id='assigneeSec-${row.id}' style="display: none;">
						 				<div id="waitMessageAsignee${row.id}" style="display: none;">
						 					<div class="cssload-square" >
												<div class="cssload-square-part cssload-square-green" ></div>
												<div class="cssload-square-part cssload-square-pink" ></div>
												<div class="cssload-square-blend" ></div>
											</div>
						 				</div>
						 				<div class='commentList' id='outerAsigneeLst-${row.id}'>
						 				</div>
						 				<div class='addCommForm'>
											<div class='buttonContainer'>
												<a href='javascript:void(0);' onclick='addAssignee(&#39;${row.id}&#39;, &#39;${communityEraContext.currentCommunity.id}&#39;);' 
						 							id='addAss${row.id}' class='commentSubmit enabled'>Assigned to</a>
											</div>
										</div>
									</div>
								<div>
								</div>
							</div>
						</div>
	   				</c:forEach>
					
	   				<div class="inboxAds">
	   					<c:if test="${communityEraContext.production}">
							<!-- CERA_RES -->
							<ins class="adsbygoogle"
							     style="display:block"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="3781277785"
							     data-ad-format="auto"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
				</div>
			</div>
				
				<div class="right-panel">
					<div class="inboxAds" style="display: inline-block; width: 100%;">
						<c:if test="${communityEraContext.production}">
							<!-- CERA_RP_R -->
							<ins class="adsbygoogle"
							     style="display:inline-block;width:300px;height:250px"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="4553333789"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
					
					<div class="inbox">
						<div class="eyebrow">
							<span><i class="fa fa-tags" style="margin-right: 2px;"></i>Popular Tags</span>
						</div>
						<div id="cloud" class="communities"></div>
						<div id="waitCloudMessage" style="display: none;">
							<div class="cssload-square" style="width: 13px; height: 13px;">
								<div class="cssload-square-part cssload-square-green" style="width: 13px; height: 13px;"></div>
								<div class="cssload-square-part cssload-square-pink" style="width: 13px; height: 13px;"></div>
								<div class="cssload-square-blend" style="width: 13px; height: 13px;"></div>
							</div>
						</div>
						<div id="cloudList" style="display: none; " class="communities"></div>
						<ul id="cloudTabs">
							<c:choose>
								<c:when test="${command.toggleList == 'true'}">
									<h3 class="selectedCloudTab" id="hCloud" style="display: none; float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
									<a href="javascript: toggle()" style="float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
									<h3 class="selectedCloudTab" style="float:right;" id="hCloudList">List</h3>
									<a href="javascript: toggle()" id="aCloudList" style="display: none; float:right; color: #66799f;">List</a>
								</c:when>
								<c:otherwise>
									<h3 class="selectedCloudTab" id="hCloud" style="float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
									<a href="javascript: toggle()" style="display: none; float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
									<h3 class="selectedCloudTab" style="display: none; float:right;" id="hCloudList">List</h3>
									<a href="javascript: toggle()" id="aCloudList" style="float:right; color: #66799f;">List</a>
							  	</c:otherwise>
							</c:choose>
						</ul>
					</div>
					
				</div>
			</div>
		<%@ include file="/WEB-INF/jspf/footer.jspf" %>
		<%@ include file="/WEB-INF/jspf/extraFooter.jspf" %>
	</body>
</html>