<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="/WEB-INF/tlds/cera_form.tld" %> 
<%@ taglib prefix="cera" uri="/WEB-INF/tlds/cera.tld" %> 
 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="author" content="${command.authorName}">
		<meta name="robots" content="index, follow">
		<meta name="google-site-verification" content="JC96M8paj34ChCcPK0EAKWSzDJqocRo6rdSqnzPbIm4" />
		<meta name="description" content="${command.subject}. ${command.metaForDescription}" />
		<meta name="keywords" content="Jhapak, Forum, Topics, community, ${command.keywords}" />
		<title>${command.subject} - Jhapak</title>
		<link rel="icon" type="image/png" href="img/link_Image.png"/>
		<link rel="canonical" href="${communityEraContext.requestUrl}" />
		<link rel="publisher" href="https://plus.google.com/+Jhapak4u"/>
		<meta property="article:publisher" content="https://www.facebook.com/EraOfCommunities" />
		
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
  				"@context" : "http://schema.org",
  				"@type" : "Article",
  				"name" : "${command.subject}",
  				"author" : {
    				"@type" : "Person",
    				"name" : "${command.authorName}"
  				},
  				"datePublished" : "${command.isoPostedOn}",
				"headline" : "${command.subject}",
  				"articleBody" : "${command.metaForDescription}",
  				"url" : "${communityEraContext.requestUrl}"
			}
		</script>
		
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary">
		<meta name="twitter:site" content="@EraCommunity">
		<meta name="twitter:title" content="${command.subject}">
		<meta name="twitter:description" content="${command.metaForDescription}">
		<meta name="twitter:url" content="${communityEraContext.requestUrl}">
		
		<!-- Open Graph data -->
		<meta property="og:title" content="${command.subject}" />
		<meta property="og:type" content="article" />
		<meta property="og:url" content="${communityEraContext.requestUrl}" />
		<meta property="og:description" content="${command.metaForDescription}" />
		<meta property="og:site_name" content="Jhapak" />
		<meta property="article:published_time" content="${command.isoPostedOn}" />
		<meta property="article:modified_time" content="${command.isoPostedOn}" />

		<meta property="fb:admins" content="100001187666357" /> 
		
		<%@ include file="/WEB-INF/jspf/commHeader.jspf" %>
		<%@ include file="/WEB-INF/jspf/header2.jspf"%>
		<%@ include file="/WEB-INF/jspf/headerTag.jspf"%>
		
		<link rel="stylesheet" media="all" type="text/css" href="css/commBnnr.css" />
		<link rel="stylesheet" type="text/css" href="css/allMedia.css" />
		
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

		<cera:taggingJS context="${communityEraContext}"/>
		<style type="text/css">
		 	.login-dialog .modal-dialog {
                width: 500px;
                height:400px;
            }
            
            .response-dialog .modal-dialog {
                width: 720px;
                height:400px;
            }
            
            form label {
            	font-size: 13px;
            }
            a.sublink {
            	position: absolute;
				right: 10px;
				bottom: 12px;
	            float:right;
	            font-size: 12px;
				font-weight: bold;
				color: #66799f;
				text-decoration: none;
            }
            
            a.sublink:hover {
			    color: #2A3A47;
			    text-decoration: none;
			}
			
			#container .left-panel .commSection .paginatedList .details {
			    float: left;
			    width: unset;
			    word-wrap: normal;
			}
			
			.rotateCss {
				-ms-transform: rotate(-45deg); /* IE 9 */
			    -webkit-transform: rotate(-45deg); /* Chrome, Safari, Opera */
			    transform: rotate(-45deg);
			}
		 </style>
		 
		<script src="ckeditor/ckeditor.js"></script>
		
		<script type="text/javascript">
			function subscribeTopic(topicId){
				$.ajax({url:"${communityEraContext.currentCommunityUrl}/forum/followThread.ajx?id="+topicId,success:function(result){
		    	    $("#subscribeTopic").html(result);
		    	  }});
			}
		
			function unSubscribeTopic(topicId){
				BootstrapDialog.show({
	                type: BootstrapDialog.TYPE_WARNING,
	                title: 'Stop following this Forum Topic',
	                message: '<p class="extraWord">You will no longer be able to receive email alerts when new responses are posted to this thread.</p>',
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
	                	label: 'Go',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                        $.ajax({url:"${communityEraContext.currentCommunityUrl}/forum/stopFollowingThread.ajx?id="+topicId,success:function(result){
	            	    	    $("#subscribeTopic").html(result);
	            	    	  }});
	                    }
	                }, {
	                	label: 'Close',
	                    action: function(dialogRef){
	                        dialogRef.close();
	                    }
	                }]
	            });
			}
			
			function likeEntry(itemId) 
			{ 
			    var isAuthenticated = $("#isAuthenticated").val();
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in.<br/> Please login first to like / unlike. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }],
		                cssClass: 'login-dialog'
		            });
			    } else {
			    	$.ajax({url:"${communityEraContext.contextUrl}/forum/likeForumItem.ajx?forumItemId="+itemId,success:function(result){
			    	    $("#likeUnike-"+itemId).html(result.likeString);
			    	    $("#likeSpan-"+itemId).html(result.likeCount);
			    	  }});
			    }
			}
		</script>
		<script type="text/javascript">
			var editor;
			function submitItemResponse(rowId,topicId,parentId, isQuote){
				var isAuthenticated = $("#isAuthenticated").val();
				
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in. Please login first to reply. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }],
		                cssClass: 'login-dialog'
		            });
			    } else {
			    				    
				var mess = '<form id="submitResponseEntry"><input type="hidden" id="topicId" name="topicId"/><input type="hidden" name="parentId" id="parentId"/>' +
				'<label for="subject">Response title (100 characters max.)</label><br /><input id="subject" name="subject" maxlength="100" style="width: 664px;"/><br /><br />' +
				'<label for="entry">Topic response</label><br/><div id="waitMessage" style="display: none;"><p class="showWaitMessage"></p></div><textarea name="body" id="body" style="display:none;"></textarea><div id="editor"></div></form>';
				
				var type = BootstrapDialog.TYPE_INFO;
				BootstrapDialog.show({
	                type: type,
	                title: 'Submit a Response',
	                message: mess,
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
		                label: 'Cancel',
		                action: function(dialog){
		            	dialog.close();
	                }
		            }, {
		                label: 'Submit',
		                cssClass: 'btn-primary',
		                action: function(dialog) {
		            	var body = editor.getData();
		            	dialog.getModalBody().find('#body').val(body);
		            	dialog.getModalBody().find('#topicId').val(topicId);
		            	dialog.getModalBody().find('#parentId').val(parentId);
		            	$.ajax({
		            	     type: "POST",
		            		 url: "${communityEraContext.requestUrl}",
		            		 data: dialog.getModalBody().find('#submitResponseEntry').serialize(),
		            		 dataType: "json",
		            	         success: function(msg){
		            			 var currentUser = document.getElementById('currentUser').value;
		            			 var responseCount = document.getElementById('responseCount').value;
		            			 
		            			 var sName = "<div class='paginatedList' id='resp-div-"+msg.responseId+"' style='margin-left:"+msg.depth*20+"px; padding: 0px;'>";
		            			 sName += "<a name='A$"+msg.responseId+"'></a><div style='padding: 10px;'><div class='leftImg'>";
		            			 if(msg.photoPresent){
									 sName += "<a href='${communityEraContext.contextUrl}/pers/connectionResult.do?id="+msg.authorId+"&backlink=ref' ><img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+msg.authorId+"' alt="+msg.authorName+" style='width: 35px; height: 35px;' /></a>"; }
								 else {
									 sName += "<img src='img/user_icon.png' style='width: 35px; height: 35px;' />";
								 }

								 sName += "</div><div class='details' style='margin-bottom: 4px;'>";
								 if(msg.subject != ''){
									 sName += "<div class='heading' style='margin-bottom: 4px;'><span style='color: #184A72; font-size: 14px;' id='respSubject-"+msg.responseId+"'>"+msg.subject+"</span><br/></div>";
								 }
								 
								 sName += "<div class='person' style='font-size: 14px;'>Posted by <a href='${communityEraContext.contextUrl}/pers/connectionResult.do?backlink=ref&amp;id="+msg.authorId+"' >"+msg.authorName+"</a> <i class='a-icon-text-separator'></i><span title='"+msg.postedOnHover+"'>"+msg.postedOn+"</span>";
								 if(msg.authorId == currentUser){
									 sName += "<i class='a-icon-text-separator'></i><a href='javascript:void(0);' onclick='editResponse(&#39;"+msg.responseId+"&#39;);' >Edit</a>";
								 }
								 sName += "</div></div>";
								 sName += "<div class='richtext' style='width: 93%; float: right;' id='body-"+msg.responseId+"'>"+msg.body+"</div></div>";

								 sName += "<div class='topSection' style='border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;'><div><ul class='bottSecLst'>";
								 sName += "<li><a href='${communityEraContext.currentCommunityUrl}/forum/forumThread.do?id="+topicId+"#A"+msg.parentId+"' >";

								 if(msg.parentAuthorPhotoPresent){
									 sName += "<img src='${communityEraContext.contextUrl}/pers/userPhoto.img?id="+msg.parentAuthorId+"' title='"+msg.parentAuthorName+"'/>";
								 } else {
									 sName += "<img src='img/user_icon.png' title='"+msg.parentAuthorName+"'/>";
								 }
								 sName += "<span title='"+msg.parentPostDateOnHover+"'>"+msg.parentPostDateON+"</span>";
								 sName += "<h4 style='margin-left: 2px;'><i class='fa fa-reply' style='margin-right: 4px;'></i>replied to</h4></a></li>";
								 sName += "<li><span id='likeSpan-"+msg.responseId+"'>"+msg.likeCount+"</span><h4>likes</h4></li>";
								 sName += "<li style='float: right; margin: 2px;'><a href='javascript:void(0);' onclick='submitItemResponse(&#39;"+msg.responseId+"&#39;, &#39;"+topicId+"&#39;, &#39;"+msg.responseId+"&#39;, &#39;1&#39;);' class='btnmain' style='height: 26px; line-height: 22px;'>";
								 sName += "<i class='fa fa-quote-left' style='margin-right: 4px;'></i>Reply With Quote</a></li>";
								 sName += "<li style='float: right; margin: 2px;'><a href='javascript:void(0);' onclick='submitItemResponse(&#39;"+msg.responseId+"&#39;, &#39;"+topicId+"&#39;, &#39;"+msg.responseId+"&#39;, &#39;0&#39;);' class='btnmain' style='height: 26px; line-height: 22px;'>";
								 sName += "<i class='fa fa-reply' style='margin-right: 4px;'></i>Reply</a></li>";

								 sName += "<li style='float: right; margin: 6px 12px;'><span>";
								 if(msg.alreadyLike){
									 sName += "<a id='likeUnike-"+msg.responseId+"' href='javascript: likeEntry("+msg.responseId+")' style='font-size: 18px; color: #2F3D4A;' ><i class='fa fa fa-thumbs-down'></i></a>";
								 } else {
									 sName += "<a id='likeUnike-"+msg.responseId+"' href='javascript: likeEntry("+msg.responseId+")' style='font-size: 18px; color: #2F3D4A;' ><i class='fa fa fa-thumbs-up'></i></a>";
								 }
								 sName += "</span></li>";
								 sName += "</ul></div></div></div>";

								 var divId = "#topicDiv";
								 if (responseCount > 0) {
									divId = "#resp-div-"+msg.lastSiblingId;
								 }
								 
								 $(sName).insertAfter(divId);
								 $("#waitMessage").hide();
								 dialog.close();
							    	},
						         beforeSend: function () {
						             $("#waitMessage").show();
						         } 
		            	       });
		            	
		            	}
		            }],
	                cssClass: 'response-dialog',
	                onshown: function(dialogRef){
					var quote = '';
					if (isQuote == 1){
						quote = $("#body-"+rowId).html();
						quote = "<blockquote>"+quote+"</blockquote>";
					}
					var config = {};
					editor = CKEDITOR.appendTo( 'editor', config, quote );
				}
	            });

			    }
			}

			function editResponse(responseId){
				var isAuthenticated = $("#isAuthenticated").val();
				
			    if (isAuthenticated == 'false') {
			    	BootstrapDialog.show({
		                type: BootstrapDialog.TYPE_DANGER,
		                title: 'Error',
		                message: '<p class="extraWord">You are not logged-in. Please login first to edit. </p>',
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }],
		                cssClass: 'login-dialog'
		            });
			    } else {
			    				    
				var mess = '<form id="submitResponseEntry"><input type="hidden" id="id" name="id"/>' +
				'<label for="subject">Response title (100 characters max.)</label><br /><input id="subject" name="subject" maxlength="100" style="width: 664px;"/><br /><br />' +
				'<label for="entry">Topic response</label><br/><div id="waitMessage" style="display: none;"><p class="showWaitMessage"></p></div><textarea name="body" id="body" style="display:none;"></textarea><div id="editor"></div></form>';
				
				var type = BootstrapDialog.TYPE_INFO;
				BootstrapDialog.show({
	                type: type,
	                title: 'Edit Response',
	                message: mess,
	                closable: true,
	                closeByBackdrop: false,
	                closeByKeyboard: false,
	                buttons: [{
		                label: 'Cancel',
		                action: function(dialog){
		            	dialog.close();
	                }
		            }, {
		                label: 'Submit',
		                cssClass: 'btn-primary',
		                action: function(dialog) {
		            	var body = editor.getData();
		            	dialog.getModalBody().find('#body').val(body);
		            	dialog.getModalBody().find('#id').val(responseId);
		            	$.ajax({
		            	     type: "POST",
		            		 url: "${communityEraContext.currentCommunityUrl}/forum/editForumResponse.ajx",
		            		 data: dialog.getModalBody().find('#submitResponseEntry').serialize(),
		            		 dataType: "json",
		            	         success: function(msg){
		            			 
		            			 $("#respSubject-"+responseId).html(dialog.getModalBody().find('#subject').val());
		     					$("#body-"+responseId).html(body);

								 
								 $("#waitMessage").hide();
								 dialog.close();
							    	},
						         beforeSend: function () {
						             $("#waitMessage").show();
						         } 
		            	       });
		            	
		            	}
		            }],
	                cssClass: 'response-dialog',
	                onshown: function(dialogRef){
					//subject
					var respTitle = $("#respSubject-"+responseId).html();
					$("#subject").val(respTitle);
					var quote = $("#body-"+responseId).html();
					var config = {};
					editor = CKEDITOR.appendTo( 'editor', config, quote );
				}
	            });

			    }
			}
			
			function joinRequest(rowId, ctype) 
			{ 
			    var ref = '${communityEraContext.contextUrl}/community/joinCommunityRequest.ajx?id='+rowId;
			    var mess = '';
			    var type = BootstrapDialog.TYPE_INFO;
			    var isAuthenticated = ${communityEraContext.userAuthenticated};
			    if (!isAuthenticated) {
			    	type = BootstrapDialog.TYPE_DANGER;
			    	mess = '<p class="extraWord">You are not logged-in.<br/> Please login first to join a community. </p>';
			    } else if (ctype == 2) {
			    	mess = '<p class="extraWord">This is a private community.<br/><br/>'+		
					'To request membership click the Go button below.  '+
					'Your request to join the community will be actioned by the community admin.  '+
					'Notification of your acceptance to the community will be sent to your email address.<br/><br />Please write a suitable message'+
					'</p><div id="statusText3"><textarea class="form-control" name="body" >I\'d like to join this community as... </textarea></div>';
					
			    } else {
			    	mess = '<p class="extraWord">This is a public community.<br/><br/>'+
				    'To join this community click the Go button below. '+
					'You will be added to the community member list and will immediately have access to the community content. '+
					'</p>';
			    }
			    if (!isAuthenticated) {
			    	BootstrapDialog.show({
		                type: type,
		                title: 'Join a community',
		                message: mess,
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    } else {
			    	BootstrapDialog.show({
		                type: type,
		                title: 'Join a community',
		                message: mess,
		                closable: true,
		                closeByBackdrop: false,
		                closeByKeyboard: false,
		                buttons: [{
		                	label: 'Go',
		                	action: function(dialogRef){
		                	var fruit = dialogRef.getModalBody().find('textarea').val();
		                	ref = ref + '&optionalComment=' + fruit;
		                	
	                        
	                        //window.location.href=ref;
	                        var xmlhttp;
        					if (window.XMLHttpRequest)
					          {// code for IE7+, Firefox, Chrome, Opera, Safari
					          xmlhttp=new XMLHttpRequest();
					          } else {// code for IE6, IE5
					          xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
					          }
						        xmlhttp.onreadystatechange=function()
						          {
						          if (xmlhttp.readyState==4 && xmlhttp.status==200)
						            {
						            dialogRef.getModalBody().html(xmlhttp.responseText);
						            }
						   		  }
						        xmlhttp.open("GET", ref , false);
						        xmlhttp.send();
						        document.getElementById("reqId-"+rowId).innerHTML=xmlhttp.responseText;
						        dialogRef.close();
	                    	}
		                }, {
		                	label: 'Close',
		                    action: function(dialogRef){
		                        dialogRef.close();
		                    }
		                }]
		            });
			    }
			}

			$(document).ready(function () {
				hljs.initHighlightingOnLoad();
			});
		</script>
	</head>

	<body id="communityEra">
		<%@ include file="/WEB-INF/jspf/topHeader.jspf" %>
		<div class="commBanr">
			<div class="bnrImg" style="background-image:url(${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&imgType=Banner&communityId=${communityEraContext.currentCommunity.id});" >
				<div class="innerPanl">
					<div class="carousel_caption">
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Private'}">
							<h4><i class="fa fa-lock" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Protected'}">
							<h4><i class="fa fa-shield" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<c:if test="${communityEraContext.currentCommunity.communityType == 'Public'}">
							<h4><i class="fa fa-globe" style="margin-right: 8px;"></i>${communityEraContext.currentCommunity.name}</h4>
						</c:if>
						<p>${communityEraContext.currentCommunity.welcomeText}</p>							
					</div>
					
					<div class="menuContainer">
						<ul id="gn-menu" class="gn-menu-main">
							<li><a href="${communityEraContext.currentCommunityUrl}/forum/showTopics.do"><i class="fa fa-comments-o" style="margin-right: 8px;"></i>Forums</a></li>
							<li>
								<nav id="menu">
						    		<input type="checkbox" id="toggle-nav"/>
						    		<label id="toggle-nav-label" for="toggle-nav"><i class="fa fa-bars"></i></label>
						    		<div class="box">
							    		<ul>
							    			<li><a href="${communityEraContext.currentCommunityUrl}/home.do"><i class="fa fa-home" style="margin-right: 8px;"></i>Home</a></li>
							    			<c:forEach items="${communityEraContext.enabledFeatureNamesForCurrentCommunity}" var="feature">
												<c:if test="${feature == 'Assignments'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/assignment/showAssignments.do"><i class="fa fa-briefcase" style="margin-right: 8px;"></i>Assignments</a></li>
												</c:if>
												<c:if test="${feature == 'Blog'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/blog/viewBlog.do"><i class="fa fa-quote-left" style="margin-right: 8px;"></i>Blogs</a></li>
												</c:if>
												<c:if test="${feature == 'Wiki'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/wiki/showWikiEntries.do"><i class="fa fa-book" style="margin-right: 8px;"></i>Wikis</a></li>
												</c:if>
												<c:if test="${feature == 'Members'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/connections/showConnections.do"><i class="fa fa-user-plus" style="margin-right: 8px;"></i>Members</a></li>
												</c:if>
												<c:if test="${feature == 'Library'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/library/showLibraryItems.do"><i class="fa fa-folder-open" style="margin-right: 8px;"></i>Library</a></li>
												</c:if>
												<c:if test="${feature == 'Events'}">
													<li><a href="${communityEraContext.currentCommunityUrl}/event/showEvents.do"><i class="fa fa-calendar-check-o" style="margin-right: 8px;"></i>Events</a></li>
												</c:if>
											</c:forEach>
							    		</ul>
						    		</div>
						    	</nav>
					    	</li>
						</ul>
					</div><!-- /container -->
						
					<div class="groups">
						<div class="picture">
							<c:choose>
								<c:when test="${communityEraContext.currentCommunity.logoPresent}">		
									<img src="${communityEraContext.contextUrl}/commLogoDisplay.img?showType=m&communityId=${communityEraContext.currentCommunity.id}" width="290" height="290" /> 
								</c:when>
								<c:otherwise>
									<img src="img/community_Image.png" id="photoImg" width="290" height="290" />
								</c:otherwise>
							</c:choose>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="container">
			<div class="left-panel">
				<input type="hidden" id="isAuthenticated" name="isAuthenticated" value="${communityEraContext.userAuthenticated}" />
				<input type="hidden" id="currentUser" value="${communityEraContext.currentUser.id}" />
				<input type="hidden" id="responseCount" value="${command.responseCount}" />
				
				<div class="commSection">
					<div class="paginatedList" style="padding: 0px; margin: 0px 0PX 10px auto;" id="topicDiv">
						<a name="A${command.id}"></a>
						<div class="topSection" >
							<div class="leftImg">							
								<c:choose>
									<c:when test="${command.photoPresent == 'Y'}">						 
										 <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.authorId}&backlink=ref">
										 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.authorId}"/></a>
									</c:when>
									<c:otherwise>
										<img src="img/user_icon.png" />
									</c:otherwise>
								</c:choose>
							</div>
							<div class="topHeader" >
								<div class="heading" style="width: 600px; color: #184A72; margin-bottom: 2px;">
									<c:if test="${command.closed}">
							 			<i class='fa fa-lock' style='margin-right: 4px; color: #20394D;' title='This topic has now been closed for new replies'></i>
							 		</c:if>
								 	<c:if test="${command.sticky}">
								 		<i class='fa fa-thumb-tack' style='margin-right: 4px; color: #20394D;' title='This topic is pinned; it will display at the top of community forum'></i>
									</c:if>
									<span style="font-size: 20px; font-weight: bold;">${command.displaySubject}</span>
								</div>
								<div class="subHeader">
									Created by 
									<a href="${communityEraContext.contextUrl}/pers/connectionResult.do?id=${command.authorId}&backlink=ref" class='memberInfo'
									title="${communityEraContext.contextUrl}/pers/connectionInfo.do?id=${command.authorId}" >${command.authorName}</a><i class='a-icon-text-separator'></i><span title="${command.postedOnHover}">${command.postedOn}</span>
								</div>
								<c:if test="${not empty command.taggedKeywords}">
									<div class="subHeader">
										<i class='fa fa-tags' style='font-size: 14px; margin-right: 4px;'></i>${command.taggedKeywords}
									</div>
								</c:if>
							</div> 
							<%--<div class='entry' style="color: #999; top: 10px; right: 10px;">#1</div> --%>
							<div class="menus">
								<ul style="margin-top: 6px;">
									<c:if test="${command.authorId == communityEraContext.currentUser.id }">
										<li><a href="${communityEraContext.currentCommunityUrl}/forum/editForumitem.do?id=${command.id}"><i class='fa fa-pencil' style='margin: 0px 4px; font-size: 14px;'></i>Edit</a></li>
									</c:if>
									<%@ include file="/WEB-INF/jspf/entire-btn-row.jspf"%>
									<c:choose>
										<c:when test="${command.currentUserSubscribed}">
											<li id ="subscribeTopic"><a href="javascript:void(0);" onclick="unSubscribeTopic(${command.topicId});"
												title="Unsubscribe from email alerts when new responses are posted to this thread" >Stop Following this Topic</a></li>
										</c:when>
										<c:otherwise>
											<li id ="subscribeTopic"><a href="javascript:void(0);" onclick="subscribeTopic(${command.topicId});" 
												title="Get email alerts when new responses are posted to this thread">Follow this Forum Topic</a></li>
										</c:otherwise>
									</c:choose>
								</ul>
							</div>
						</div>
						
						<div class="inboxAds">
							<c:if test="${communityEraContext.production}">
								<!-- CERA_RES -->
								<ins class="adsbygoogle"
								     style="display:block"
								     data-ad-client="ca-pub-8702017865901113"
								     data-ad-slot="3781277785"
								     data-ad-format="auto"></ins>
								<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
								</script>
							</c:if>
						</div>
						<div class="richtext" style="float: left;min-width: 450px; margin-bottom:10px; padding: 10px;">${command.displayBody}</div>
						
						<div class="topSection" style="border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;">
							<div>
								<ul class="bottSecLst">
									<li>
										<c:choose>
											<c:when test="${command.photoPresent == 'Y'}">						 
												 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.authorId}" title="${command.authorName}"/>
											</c:when>
											<c:otherwise>
												<img src="img/user_icon.png" title="${command.authorName}"/>
											</c:otherwise>
										</c:choose>
										<span title="${command.postedOnHover}">${command.postedOn}</span>
										<h4 style="margin-left: 16px;">created</h4>
									</li>
									<c:if test="${command.responseCount > 0}">
										<li>
											<c:choose>
												<c:when test="${command.lastPostPhotoPresent == 'Y'}">						 
													 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${command.lastPosterId}" title="${command.lastPosterName}"/>
												</c:when>
												<c:otherwise>
													<img src="img/user_icon.png" title="${command.lastPosterName}"/>
												</c:otherwise>
											</c:choose>
											<span title="${command.lastPostDate}">${command.lastPostedOn}</span>
											<h4 style="margin-left: 16px;">last reply</h4>
										</li>
									</c:if>
									<li>
										<span title="${command.responseCount}">${command.responseCount}</span>
										<h4>replies</h4>
									</li>
									<li>
										<span title="Last viewed at ${command.lastVisitTime}">${command.visitCount}</span>
										<h4>views</h4>
									</li>
									<li>
										<span id="likeSpan-${command.id}">
											${command.likeCount}
										</span>
										<h4>likes</h4>
									</li>
									<c:if test="${!command.closed}">
										<li style="float: right; margin: 2px;">
											<a href="javascript:void(0);" onclick="submitItemResponse('${command.id}', '${command.id}', '${command.id}', '0');" class="btnmain" style="height: 26px; line-height: 22px"><i class="fa fa-reply" style="margin-right: 4px;"></i>Reply</a>
										</li>
									</c:if>
									<li style="float: right; margin: 6px 12px;">
										<span>
											<c:choose>
												<c:when test="${command.alreadyLike}">
													<a id="likeUnike-${command.id}" href="javascript: likeEntry(${command.id})" style="font-size: 18px; color: #2F3D4A;" ><i class="fa fa fa-thumbs-down"></i></a>
												</c:when>
												<c:otherwise>
													<a id="likeUnike-${command.id}" href="javascript: likeEntry(${command.id})" style="font-size: 18px; color: #2F3D4A;" ><i class="fa fa fa-thumbs-up"></i></a>
												</c:otherwise>
											</c:choose>
										</span>
									</li>
								</ul>
							</div>
							<div>
							</div>
						</div>
					</div>
					
					<c:set var="flag" value="0"/>
						<c:forEach items="${command.items}" var="row" varStatus="status">
							<a name="A${row.id}"></a><div class="paginatedList" style="margin-left:${row.depth*20}px; padding: 0px;" id="resp-div-${row.id}">
								
								<div style='padding: 10px;'>
									<div class='leftImg'>
										<c:choose>
											<c:when test="${row.photoPresent == 'Y'}">	
												<c:url value="${communityEraContext.contextUrl}/pers/userPhoto.img" var="photoUrl">	<c:param name="id" value="${row.authorId}"/> </c:url>
												<img src="${photoUrl}" alt="${row.authorName}" style="width: 35px; height: 35px;" />	
											</c:when>
											<c:otherwise>
												<img src="img/user_icon.png" style="width: 35px; height: 35px;" />
											</c:otherwise>
										</c:choose> 
									</div>
									<div class="details" style="margin-bottom: 4px;">
										<c:if test="${not empty row.subject}">
											<div class="heading">
												<span style='color: #184A72; font-size: 14px;' id='respSubject-${row.id}'>${row.subject}</span><br/>
											</div>
										</c:if>
										<div class="person" style="font-size: 14px;">
											Posted by <a href="${communityEraContext.contextUrl}/pers/connectionResult.do?backlink=ref&amp;id=${row.authorId}" >${row.authorName}</a> <i class='a-icon-text-separator'></i> ${row.postedOn}
											<c:if test="${row.authorId == communityEraContext.currentUser.id }">
												<i class='a-icon-text-separator'></i><a href="javascript:void(0);" onclick="editResponse(${row.id});">Edit</a>
											</c:if>
										</div>
									</div>
									<%--<div class='entry' style="font-size: 12px; color: #999; top: 10px; right: 10px; float: right;" >#${status.index+2}</div> --%>
									<div class="richtext" style="width: 93%; float: right;" id="body-${row.id}">${row.body}</div>
								</div>
								<div class="topSection" style="border-width: 1px 0px 0px; border-radius: 0px 0px 3px 3px; margin: 0px;">
									<div>
										<ul class="bottSecLst">
											<li>
												<a href="${communityEraContext.currentCommunityUrl}/forum/forumThread.do?id=${command.topicId}#A${row.parentId}">
													<c:choose>
														<c:when test="${row.parentAuthorPhotoPresent == 'Y'}">						 
															 <img src="${communityEraContext.contextUrl}/pers/userPhoto.img?id=${row.parentAuthorId}" title="${row.parentAuthorName}"/>
														</c:when>
														<c:otherwise>
															<img src="img/user_icon.png" title="${row.parentAuthorName}"/>
														</c:otherwise>
													</c:choose>
													<span title="${row.parentPostDateOnHover}">${row.parentPostDateON}</span>
													<h4 style="margin-left: 2px;"><i class="fa fa-reply" style="margin-right: 4px;"></i>replied to</h4>
												</a>
											</li>
											<li>
												<span id="likeSpan-${row.id}">
													${row.itemLike}
												</span>
												<h4>likes</h4>
											</li>
											<c:if test="${!command.closed}">
												<li style="float: right; margin: 2px;">
													<a href="javascript:void(0);" onclick="submitItemResponse('${row.id}', '${row.topicId}', '${row.id}', '1');" class="btnmain" style="height: 26px; line-height: 22px"><i class="fa fa-quote-left" style="margin-right: 4px;"></i>Reply With Quote</a>
												</li>
												<li style="float: right; margin: 2px;">
													<a href="javascript:void(0);" onclick="submitItemResponse('${row.id}', '${row.topicId}', '${row.id}', '0');" class="btnmain" style="height: 26px; line-height: 22px"><i class="fa fa-reply" style="margin-right: 4px;"></i>Reply</a>
												</li>
											</c:if>
											<li style="float: right; margin: 6px 12px;">
												<span>
													<c:choose>
														<c:when test="${row.alreadyLike > 0}">
															<a id="likeUnike-${row.id}" href="javascript: likeEntry(${row.id})" style="font-size: 18px; color: #2F3D4A;" ><i class="fa fa fa-thumbs-down"></i></a>
														</c:when>
														<c:otherwise>
															<a id="likeUnike-${row.id}" href="javascript: likeEntry(${row.id})" style="font-size: 18px; color: #2F3D4A;" ><i class="fa fa fa-thumbs-up"></i></a>
														</c:otherwise>
													</c:choose>
												</span>
											</li>
										</ul>
									</div>
									<div>
									</div>
								</div>
							</div>
		   				</c:forEach>
		   				
		   				<div class="inboxAds">
		   					<c:if test="${communityEraContext.production}">
								<!-- CERA_RES -->
								<ins class="adsbygoogle"
								     style="display:block"
								     data-ad-client="ca-pub-8702017865901113"
								     data-ad-slot="3781277785"
								     data-ad-format="auto"></ins>
								<script>
								(adsbygoogle = window.adsbygoogle || []).push({});
								</script>
							</c:if>
						</div>
				</div>
			</div>
				
				<div class="right-panel">
					<div class="inboxAds" style="display: inline-block; width: 100%;">
						<c:if test="${communityEraContext.production}">
							<!-- CERA_RP_R -->
							<ins class="adsbygoogle"
							     style="display:inline-block;width:300px;height:250px"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="4553333789"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
					
					<div class="inbox">
						<div class="eyebrow">
							<span><i class="fa fa-tags" style="margin-right: 2px;"></i>Popular Tags</span>
						</div>
						<div id="cloud" class="communities"></div>
						<div id="waitCloudMessage" style="display: none;">
							<div class="cssload-square" style="width: 13px; height: 13px;">
								<div class="cssload-square-part cssload-square-green" style="width: 13px; height: 13px;"></div>
								<div class="cssload-square-part cssload-square-pink" style="width: 13px; height: 13px;"></div>
								<div class="cssload-square-blend" style="width: 13px; height: 13px;"></div>
							</div>
						</div>
						<div id="cloudList" style="display: none; " class="communities"></div>
						<ul id="cloudTabs">
							<c:choose>
								<c:when test="${command.toggleList == 'true'}">
									<h3 class="selectedCloudTab" id="hCloud" style="display: none; float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
									<a href="javascript: toggle()" style="float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
									<h3 class="selectedCloudTab" style="float:right;" id="hCloudList">List</h3>
									<a href="javascript: toggle()" id="aCloudList" style="display: none; float:right; color: #66799f;">List</a>
								</c:when>
								<c:otherwise>
									<h3 class="selectedCloudTab" id="hCloud" style="float:left;">Cloud<i class='a-icon-text-separator'></i></h3>
									<a href="javascript: toggle()" style="display: none; float:left; color: #66799f;" id="aCloud">Cloud<i class='a-icon-text-separator'></i></a>
									<h3 class="selectedCloudTab" style="display: none; float:right;" id="hCloudList">List</h3>
									<a href="javascript: toggle()" id="aCloudList" style="float:right; color: #66799f;">List</a>
							  	</c:otherwise>
							</c:choose>
						</ul>
					</div>
					
					<div class="inboxAds" style="display: inline-block; width: 100%;">
						<c:if test="${communityEraContext.production}">
							<!-- CERA_RP_R -->
							<ins class="adsbygoogle"
							     style="display:inline-block;width:300px;height:250px"
							     data-ad-client="ca-pub-8702017865901113"
							     data-ad-slot="4553333789"></ins>
							<script>
							(adsbygoogle = window.adsbygoogle || []).push({});
							</script>
						</c:if>
					</div>
				</div>
			</div>
		<%@ include file="/WEB-INF/jspf/footer.jspf" %>
		<%@ include file="/WEB-INF/jspf/extraFooter.jspf" %>
	</body>
</html>